### PR TITLE
travis: simplified test script, updated node version

### PR DESCRIPTION
**Pull request by coderaiser**
**package scripts**:
```
./node_modules/karma/bin/karma start --single-run --browsers PhantomJS ->
karma start --single-run --browsers PhantomJS`
```
**node**:
`0.10` -> `4`

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 94bb9541b0238a82f222075d98c1a94f372e0cce
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at http://karma-runner.github.io/0.13/dev/git-commit-msg.html

---
This message was auto-generated by https://gitcop.com

**Comment by Dignifiedquire** [comment]
Thanks, could you change the commit message to something like this. `docs(travis): simplify test script, update node version`

**Comment by coderaiser** [comment]
Done.

**Comment by Dignifiedquire** [comment]
Thanks :octocat:

**Pull request merged**
