### PR TITLE
Small code tweaks

### PR DESCRIPTION
**Pull request by jasonLaster**
Hey guys, here are some small code tweaks that I came across while looking into writing a pre-processor. Hopefully they conform to your style. If not, feel free to close the PR.

Cleanups:
+ Moved server.js event listeners and function definitions to the top
+ Named anonymous functions

### CODE REVIEW

**Comment by jasonLaster** [comment]
signed it!

**Comment by Dignifiedquire** [comment]
Thanks, could you please

* change the commit message to follow our [convention](http://karma-runner.github.io/0.12/dev/git-commit-msg.html)
* change the base branch to `canary`, as I'm not merging anymore code into `master` as I'm about to move `canary` to stable.

**Comment by jasonLaster** [comment]
Surr

**Comment by Dignifiedquire** [comment]
Btw you can continue using `master` as I just did the release a few hours ago

**Comment by jasonLaster** [comment]
Just cleaned the commit. Left the scope blank because I wasn't sure

**Comment by Dignifiedquire** [comment]
Hey can you change the commit message to `refactor: ..` please and rebase onto the latest master? Thanks

**Comment by jasonLaster** [comment]
should be good.

**Comment by Dignifiedquire** [comment]
Thanks, but it seems there are still conflicts, could you recheck if you have rebased it onto the latest master please?

**Comment by Dignifiedquire** [comment]
Closing due to inactivity

**Pull request closed without merging**
