### PR TITLE
fix(plugin): fix plugin loading bug #2221

### LINKED ISSUE #2221: could not load plugins while karma not installed in node_modules/karma
### Expected behavior

loading plugins even if karma installed in sub directory in node_modules
### Actual behavior

can not load plugins
### Enviroment Details
- Karma version 1.1.0 and 0.0.13 (output of `karma --version`):
### Steps to reproduce the behaviour

karma installed by a npm installing tool, located in `node_modules/.npminstall/karma`, the same as all other karma plugins.

### PR DESCRIPTION
**Pull request by zincli**
Closes #2221

### CODE REVIEW

**Comment by dignifiedquire** [comment]
By the way if you force push `git push -f` you can update the branch with new commits without making a new PR everytime :)

**Comment by zincli** [comment]
@dignifiedquire Oh thanks! Got it.

**Comment by zincli** [comment]
ci always failed in node@0.12 or 0.10, but i got this passed in local environment. what should i do ?

**Comment by dignifiedquire** [comment]
Not sure appveyor is sometimes not very nice :/

**Pull request closed without merging**
