### PR TITLE
docs: Include Node 5.x versions

### PR DESCRIPTION
**Pull request by buzinas**
Already updated the 5.x version into FAQ, but the Intro is out-of-date yet.

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: fb02cff1fafae027f0c7f7850a3da9de79e4df27
  * Your commit message body contains a line that is longer than 80 characters
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at http://karma-runner.github.io/0.13/dev/git-commit-msg.html

---
This message was auto-generated by https://gitcop.com

**Comment by Dignifiedquire** [comment]
Thanks, can you change the commit message to follow our [convention](http://karma-runner.github.io/0.13/dev/git-commit-msg.html)

**Comment by buzinas** [comment]
Ok, fixed the problems!

**Comment by Dignifiedquire** [comment]
@buzinas sorry I meant the commit message itself via git, not the title of the PR

**Pull request closed without merging**
