### PR TITLE
add plain Reporter

### PR DESCRIPTION
**Pull request by bySabi**
A plain reporter that only show TOTAL output result.
This reporter must replace `progress` reporter as default reporter.
Create like a workaround of `progress` issue https://github.com/karma-runner/karma/issues/1411

### CODE REVIEW

**Comment by bySabi** [comment]
I signed it!)

**Comment by dignifiedquire** [comment]
@bySabi thank you. I don't fully understand though why we need this reporter and why it needs to replace the default progress reporter, could you explain please?

**Comment by bySabi** [comment]
@dignifiedquire current `progress` reporter is broken, his output is not concistent and recommend using `dot` reporter  like a workaround is not suitable for everyone. 

I wish have a simple "plain" reporter that only show TOTAL test output without progress or dots.

**Comment by dignifiedquire** [comment]
@bySabi right, but that doesn't mean we should change the default for everyone.

**Comment by bySabi** [comment]
I changed that, `plain` is not longer default reporter.

**Comment by johnjbarton** [comment]
Sorry this did not work out. I'm going to close a lot of older pull requests as the source code has changed a lot over the last year.
Thanks!

**Pull request closed without merging**
