### PR TITLE
Added fixed regex for documentation example matching test file suffix…

### LINKED ISSUE #1474: Inconsistent regex and test file naming in plus/RequireJS documentation
It's a minor issue but it catches me every time I start a new project. The [documentation example for RequireJS](http://karma-runner.github.io/0.12/plus/requirejs.html) names test files with a  **Spec.js** suffix, but the regex to filter the loaded files is...

```regex
test\.js$
```

Clearly it never loads test files. PR incoming.

### PR DESCRIPTION
**Pull request by jfarid27**
…. fixes #1474.

Also, I'm not sure if this is where this should go. I branched off canary, but I can re-write a PR for a different branch if necessary.

### CODE REVIEW

**Comment by Dignifiedquire** [comment]
Thanks. Could you please change the commit message to follow our guidelines?
Also wouldn't it make more sense to change the test files to use lowercase `spec` as there are still file systems that are case insensitive.

**Comment by jfarid27** [comment]
I signed it!

**Comment by jfarid27** [comment]
Closing to resend using commit message guidelines.

**Comment by Dignifiedquire** [comment]
@jfarid27 you can use [amend](https://help.github.com/articles/changing-a-commit-message/) or [interactive rebase](https://help.github.com/articles/about-git-rebase/) followed by a [force push](http://git-scm.com/docs/git-push) to update on the same branch, without the need of a new PR.

**Pull request closed without merging**
