### PR TITLE
feat(static): Support media queries

### PR DESCRIPTION
**Pull request by unional**
Add meta tags in static html files

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 12fb2a06aa9ef2a9ab633fb7e32777c399e4a071
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at http://karma-runner.github.io/0.13/dev/git-commit-msg.html

---
This message was auto-generated by https://gitcop.com

**Comment by unional** [comment]
Sorry about the last two PR, apparently I can't spell.

But the message still has problem?

**Comment by Dignifiedquire** [comment]
Yeah, the issue is that it expects a scope, so something like `feat(client): Support media queries`.

By the way you don't have to make new PRs if you just want to change the commit message, take a look at this https://help.github.com/articles/changing-a-commit-message/

**Comment by unional** [comment]
Thanks.  I have updated the commit message.  Never tried to do a force push on amend, learned new stuff. :)
I use `static` as the scope.  Would that be ok?  According to the doc, `scope` should be optional thou.

**Comment by Dignifiedquire** [comment]
Yes in general it's optional, but the bot is not that intelligent ;)
Looks fine now thanks

**Comment by Dignifiedquire** [comment]
I will merge this into the canary branch tomorrow, and release it as such, as this could be breaking tests if people rely on it not being present.

**Comment by unional** [comment]
What is the purpose / target of the canary branch?

**Comment by Dignifiedquire** [comment]
It's a preview of the next release which allows for breaking changes. It'll have a version like `0.14.0-rc.0`. And ar some point it will be released as new stable release, i.e `0.14.0`

**Comment by Dignifiedquire** [comment]
I changed my mind, let's try this in stable. Published as [0.13.8](https://github.com/karma-runner/karma/releases/tag/v0.13.8)

**Pull request merged**
