### PR TITLE
fix(karma): Fix issue regarding escape quotes

### PR DESCRIPTION
**Pull request by Moumi**
Change a line to escape single quote characters in filenames.

Closes *[#1876](https://github.com/karma-runner/karma/issues/1876)*

### CODE REVIEW

**Comment by dignifiedquire** [comment]
Thanks, can you squash the two commits into one please?

**Comment by Moumi** [comment]
@dignifiedquire I have squashed them together. Never done it before, so I hope it all went well. :wink:

**Comment by dignifiedquire** [comment]
Thanks :octocat: looks good.

**Comment by alancutter** [comment]
Also this should probably use JSON.stringify() instead of hand rolled replace() calls. Files with newlines in them will also cause problems.

**Pull request merged**
