### PR TITLE
style(client/karma): Fix indentation

### PR DESCRIPTION
**Pull request by thetrevdev**
Change indentation to pass updated eslint

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: bafebcbe2b42415b206077e359d451b87e8efda8
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at http://karma-runner.github.io/0.13/dev/git-commit-msg.html

---
This message was auto-generated by https://gitcop.com

**Comment by Dignifiedquire** [comment]
Thanks, could you rebase onto the latest master and fixup the commit message please (there is a space missing after the colon)

**Comment by thetrevdev** [comment]
Done

**Comment by Dignifiedquire** [comment]
Thanks

**Pull request merged**
