### PR TITLE
fix(config): Default remaining client options if any are set

### LINKED ISSUE #961: client.captureConsole isn't defaulted correctly if client config is defined
The new client.captureConsole setting added in #850 (for #744) doesn't get defaulted correctly if you have any client options set. e.g:

    client: {
      args: [ /* some args */ ],
    },

In this case client.captureConsole is undefined, and you never see any console messages even though it's supposed to be `true` by default.

This possibly affects all default arguments that are nested.

### PR DESCRIPTION
**Pull request by firesock**
Closes #961

### CODE REVIEW

**Comment by firesock** [comment]
Not sure what broke 0.12 node build, any ideas?

**Comment by nemoDreamer** [comment]
:panda_face:

**Comment by firesock** [comment]
@maksimr Mainly wanted to keep the defaults in the same place in the file and access in a similar way to other defaults. Is it preferable to just use a simple top-level variable?

**Comment by Dignifiedquire** [comment]
lgtm

**Comment by maksimr** [comment]
@firesock all properties of instance `Config` user can change in `karma.config.js`, I dont think make `defaultConfig` as *public* property of `config` good idea.

Thanks!

**Comment by Dignifiedquire** [comment]
#merge

**Comment by firesock** [comment]
Sorry, was away for a while, couldn't pick up the comment. It was merged anyway, so I assume that's fine. Let me know if you still want the changes?

**Pull request merged**
