### PR TITLE
test(e2e): Add basic cucumber setup for better e2e testing.

### PR DESCRIPTION
**Pull request by Dignifiedquire**
Move all e2e tests to [Cucumber](https://github.com/cucumber/cucumber-js) feature descriptions.

* [x] ~~angular-scenario~~
* [x] basic
* [x] ~~browserstack~~
* [x] pass-opts
* [x] reconnecting
* [x] syntax-error
* [x] timeout

### CODE REVIEW

**Comment by vojtajina** [comment]
What is the `test/e2e/proxy` folder?
You said you added the "timeout" test but I can't see it. Where is it?

**Comment by vojtajina** [comment]
@Dignifiedquire

**Comment by Dignifiedquire** [comment]
> What is the test/e2e/proxy folder?
> You said you added the "timeout" test but I can't see it. Where is it?

@vojtajina Sorry about that, not sure why I thought I finished it. 
I've added the correct `proxy` and `timeout` features now.

**Comment by vojtajina** [comment]
#merge

**Comment by vojtajina** [comment]
Thank you sir @Dignifiedquire - good stuff!

**Comment by Dignifiedquire** [comment]
You're very welcome. It took long enough :laughing:

**Pull request merged**
