### PR TITLE
feat(scope): Pass CLI arguments to karma.config.js. Closes #1561

### LINKED ISSUE #1561: Give karma.config.js access to command line arguments
Currently, the ```config``` argument passed into karma.config.js is an empty object, that gets filled out. It would be beneficial, to have access to command line arguments from within the configuration, through the passed ```config``` object, as this would allow custom logic, based on those arguments to be applied. 

Example scenario: There are two test suites (eg. unit and component) in two different folders. It's desired to run only the selected test suite. This could easily be achieved by passing an argument on the command line (like ```suite=unit```), that karma.config.js would have access to and would set the proper value on the ```config.files``` property.

What do people think about it? The implementation of this would be very straightforward (basically a one-liner).

### PR DESCRIPTION
**Pull request by danielsiwiec**
Set up config object with CLI arguments, before passing it to karma config

### CODE REVIEW

**Comment by Dignifiedquire** [comment]
Thanks, this looks good, just one thing could you reformat your commit message to 

```
feat(config): Pass CLI arguments to `karma.config.js`. 

Closes #1561
```

**Comment by danielsiwiec** [comment]
Done

**Comment by danielsiwiec** [comment]
@Dignifiedquire any idea what does CI failures mean? Seem to be unrelated.

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: eb03db6913aa926da70f3d98eac96f719bbf7fd9
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: e410911908bf677acba10c547190c70e702f75e5
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at http://karma-runner.github.io/0.13/dev/git-commit-msg.html

---
This message was auto-generated by https://gitcop.com

**Comment by danielsiwiec** [comment]
@Dignifiedquire I rebased the fork to keep it in sync with upstream, hence the warning above about cla. Anything I can do about it?

**Comment by danielsiwiec** [comment]
@Dignifiedquire Any idea what that AppVeyor failure means?

**Comment by scottohara** [comment]
@danielsiwiec According to the Travis logs, it appears to be failing some eslint checks:

test/unit/config.spec.js
   42:33  error  Requires a space after "{"               block-spacing
   42:77  error  Requires a space before "}"              block-spacing
  148:70  error  Block must not be padded by blank lines  padded-blocks

**Comment by scottohara** [comment]
Looking at the history of the AppVeyor build, it doesn't seem like it has ever passed?

**Comment by danielsiwiec** [comment]
@scottohara Yeah, I just noticed that and just fixed it. I was puzzled by the AppVeyor failure though:

```
Specify a project or solution file. The directory does not contain a project or solution file.
```

Any idea what it means?

**Comment by Dignifiedquire** [comment]
@danielsiwiec Apvoyer is not properly set up, still working on that, that's why it's failing.

Everything else looks good now, thanks :octocat:

**Pull request merged**
