### PR TITLE
fix: install semantic-release as a regular dev dependency

### PR DESCRIPTION
**Pull request by devoto13**
Also changed global executable to NPM script as global executable will not be available unless the package is installed globally (with `npm i -g`).

### CODE REVIEW

**Comment by Den-dp** [comment]
Here is my 2 cents... There is a more elegant way of solving this via npx https://github.com/karma-runner/karma/commit/ad777f066e50eb7e830dd0d30c60625f76753cd9#r38206422

**Comment by johnjbarton** [comment]
Could you elaborate? I don't know `npx`.

**Comment by devoto13** [comment]
It is a way to do ad-hoc global package installation, run it in and then uninstall in one command.
I still think that having all these packages in the lock file is cleaner and safer solution. As we always get predictable versions and dependency tree.

**Comment by Den-dp** [comment]
@johnjbarton https://medium.com/@maybekatz/introducing-npx-an-npm-package-runner-55f7d4bd282b

@devoto13 so yes, that is just one way of doing it. Assuming the fact that semantic-release packages adhere to semver - it should be safe just to specify a major package version in npx call.

Pros 👍
* More lightweight and easy-to-maintain configuration via one line.

Cons 👎
* Theoretically some transitive dependency may break one day, so pulling the latest every time is less safe than installing it as a deps.

Just found that `semantic-release` docs suggests using a mixed approach with installing all deps but running it via npx instead of adding semantic-release script (so npx will use packages from node_modules) https://semantic-release.gitbook.io/semantic-release/usage/installation#local-installation But that's minor

**Pull request merged**
