### PR TITLE
fix: unignore client directory

### PR DESCRIPTION
**Pull request by remcohaszing**
This directory was missing when trying to use karma from the latest master.

### CODE REVIEW

**Comment by remcohaszing** [comment]
By *using karma from the latest master* I meant using it as a git dependency. Since the #2899 has not yet been published, I decided to depend on the latest master.

```
npm install github:karma-runner/karma
```

However, when trying to run karma from this point, it crashed because it was unable to find the `client` directory.

```
$ karma start --single-run

START:

webpack: Compiled successfully.
webpack: Compiling...
webpack: wait until bundle finished: 
webpack: wait until bundle finished: 
30 03 2018 09:50:48.445:INFO [karma]: Front-end scripts not present. Compiling...

webpack: Compiled successfully.
30 03 2018 09:50:49.390:ERROR [karma]: { Error: Cannot find module '/home/remco/Projects/appsemble/app/node_modules/karma/client/main.js' from '/home/remco/Projects/appsemble/app'
    at /home/remco/Projects/appsemble/app/node_modules/browser-resolve/node_modules/resolve/lib/async.js:55:21
    at load (/home/remco/Projects/appsemble/app/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/home/remco/Projects/appsemble/app/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /home/remco/Projects/appsemble/app/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:170:21)
  stream: 
   Labeled {
     _readableState: 
      ReadableState {
        objectMode: true,
        highWaterMark: 16,
        buffer: BufferList { length: 0 },
        length: 0,
        pipes: [Labeled],
        pipesCount: 1,
        flowing: true,
        ended: false,
        endEmitted: false,
        reading: true,
        sync: false,
        needReadable: true,
        emittedReadable: false,
        readableListening: false,
        resumeScheduled: false,
        destroyed: false,
        defaultEncoding: 'utf8',
        awaitDrain: 0,
        readingMore: false,
        decoder: null,
        encoding: null },
     readable: true,
     _events: 
      { end: [Array],
        error: [Function],
        data: [Function: ondata],
        _mutate: [Function] },
     _eventsCount: 4,
     _maxListeners: undefined,
     _writableState: 
      WritableState {
        objectMode: true,
        highWaterMark: 16,
        finalCalled: false,
        needDrain: false,
        ending: true,
        ended: true,
        finished: true,
        destroyed: false,
        decodeStrings: true,
        defaultEncoding: 'utf8',
        length: 0,
        writing: false,
        corked: 0,
        sync: false,
        bufferProcessing: false,
        onwrite: [Function],
        writecb: null,
        writelen: 0,
        bufferedRequest: null,
        lastBufferedRequest: null,
        pendingcb: 0,
        prefinished: true,
        errorEmitted: false,
        bufferedRequestCount: 0,
        corkedRequestsFree: [CorkedRequest] },
     writable: false,
     allowHalfOpen: true,
     _options: { objectMode: true },
     _wrapOptions: { objectMode: true },
     _streams: [ [Deps] ],
     length: 1,
     label: 'deps' } }
```

It did work when I installed my fork:

```
npm install 'github:remcohaszing/karma#restore-client'
```

**Comment by johnjbarton** [comment]
AFAICT, your use case is intermediate between "run from the git clone" (supported by dynamic compile) and "run from npm install" (supported by published files).

If you want to support that mode of running it seems ok.  We need to sort out why the dynamic compile fails for you. The log shows `webpack: Compiled successfully.` so webpack is being invoked. But somehow the result is not being loaded and used correctly. 

Maybe you just need to run another npm command.  Try `npm build`

**Comment by remcohaszing** [comment]
My only goal is to support on the latest master, because source maps are broken when using the latest published version.

Npm supports installing npm packages from git. As far as I understand from the comments this is something that’s not being supported by karma. This PR fixes that.

If karma requires a `postinstall` step, this should be added to karma’s *package.json*. However, as far as I understand, the `build` step is more of a `prepublish` step. (Side note: I think it should be renamed.) I’m not even sure how this works when installing git dependencies using npm.

The real fix is to publish a new version of Karma, because that would mean one no longer has to depend on a git version to include #2899.

**Comment by johnjbarton** [comment]
https://docs.npmjs.com/cli/install
```
npm install <git remote url>:
...
If the package being installed contains a *prepare* script,
 its *dependencies* and *devDependencies* will be installed,
 and the prepare script will be run, before the package is packaged and installed.
```
So perhaps you can try changing the `package.json` to add 
```js
   "prepare": "grunt build",
```

**Comment by remcohaszing** [comment]
Renaming the `build` script to `prepare` also works. I’m closing this in favour of #2972.

**Pull request closed without merging**
