### PR TITLE
fix(deps): update socket.io to version 2.0.3

### PR DESCRIPTION
**Pull request by kevinsalter**
Fixes issue #2777

### CODE REVIEW

**Comment by kevinsalter** [comment]
I signed it!

**Comment by dignifiedquire** [comment]
We require browser support down to IE 7, can you confirm that this is still given with this new socket.io version? otherwise I don't think we can easily upgrade

**Comment by tonyd256** [comment]
@dignifiedquire I realize this may not be your decision but would you be able to change your support requirements? Looking at a bunch of browser usage statistics, IE 7 doesn't even register anymore as a used browser.
https://www.netmarketshare.com/browser-market-share.aspx?qprid=2&qpcustomd=0
https://www.w3counter.com/trends
And many move available here: https://en.wikipedia.org/wiki/Usage_share_of_web_browsers

Also, even Microsoft themselves don't support it as well as a few versions above it.
https://www.microsoft.com/en-us/WindowsForBusiness/End-of-IE-support

**Comment by bengourley** [comment]
> We require browser support down to IE 7, can you confirm that this is still given with this new socket.io version?

@dignifiedquire as far as I can see, socket.io still supports IE6+7. Their test suite/CI has passing automated tests for both these browsers: 

image

Would be great to get this merged and published!
___

Thanks @kevinsalter for putting this PR together, I'm currently using your fork until this gets merged 👍

**Comment by acoard** [comment]
Any update on this?  The current version of Socket.io being used, 1.7.4, relies on debug@2.3.3 [which has a known ReDos vulnerability](https://snyk.io/vuln/npm:debug:20170905).

**Comment by mattgrande** [comment]
The version of socket.io being used also relies on `ws@1.1.2` which _also_ [has a known DoS vulnerability](https://nodesecurity.io/advisories/550).

**Comment by johnjbarton** [comment]
Thanks @kevinsalter, to get around being unable to re-build in appveyor, I stole your thunder in #2880

**Comment by kevinsalter** [comment]
@johnjbarton all good, happy to see this go out 😄

**Pull request closed without merging**
