### PR TITLE
fix(debug-runner): support asynchronous tests in the debug runner

### LINKED ISSUE #2811: One failing test causes other async tests to fail in the Karma DEBUG RUNNER
Consider the following tests (in Jasmine), where the first is synchronous and the second is asynchronous:

```
describe("The system", function() {
    
    it("should fail", function() {
        expect(true).toBe(false);
    });

    it("should succeed", function(done) {
        setTimeout(function() {
            expect(1).toBe(1);
            done();
        }, 10);
    });
});
```

### Expected behaviour
- When I run the tests in the default runner, I expect the first test to fail and the second test to pass.
- When I run the tests in the Karma DEBUG RUNNER, I expect the first test to fail and the second test to pass.

### Actual behaviour
- When I run the tests in the default runner, the first test fails and the second test passes, as expected.
- When I run the tests in the Karma DEBUG RUNNER, **both** tests fail. The error message for the second test is the same failure message that caused the first test to fail:

```
Uncaught Expected true to be false.
    at UserContext.<anonymous> (http://localhost:9876/base/test.spec.js:4:22) thrown
```

### Environment Details

- Karma version (output of `karma --version`): 1.7.0
- `karma.config.js` file is default out of the box, configured to load '*.js' files.

### Steps to reproduce the behaviour

1. Create a new application using `npm init`
2. `npm install karma karma-jasmine jasmine-core karma-chrome-launcher --save-dev`
3. Create a new file called `test.spec.js` and add the test code that is listed above.
4. Run `karma init` and accept all defaults. Enter `*.js` and `*.spec.js` as files location.
5. Add `"test": "karma start"` to the package.json `scripts` section.
6. run `npm run test`
7. Click the `Debug` button to open the Karma DEBUG RUNNER.
8. In the console of Google Chrome, you can now see the error messages.

### PR DESCRIPTION
**Pull request by daanstolp**
Use console.error to log errors to the console instead of throwing
an error. This makes sure that errors are scoped properly for
asynchronous tests, instead of showing up as uncaught errors on
all asynchronous tests.

Fixes #2811

### CODE REVIEW

**Comment by daanstolp** [comment]
The appveyor build fails with an error that *seems* unrelated to the changes. Is there any way to retry the build?

**Comment by daanstolp** [comment]
What's causing the wait on the CLA check? Is there anything I can do to move this forward?

**Comment by dignifiedquire** [comment]
@daanstolp not sure what the issue with that check is, merged now, thank you

**Comment by juanca** [comment]
Any chance this can be a patch release? Or released in general?

**Comment by juanca** [comment]
I apologize if this is the wrong channel of communication (and would greatly appreciate some feedback!): any chance this can be released as a patch? Or is this undergoing testing?

**Comment by daanstolp** [comment]
Just wanted to add a "me too": me and my team are also eagerly awaiting the availability of this fix. When can we expect this to be released?

**Comment by juanca** [comment]
Hello fellow karma maintainers! 

Can I get a quick update on this issue? 

@daanstolp Have you by chance released a scoped package for this fix?

**Comment by johnjbarton** [comment]
AFAICT this was released 
https://github.com/karma-runner/karma/releases/tag/1.7.1

**Comment by juanca** [comment]
I'll check it out. Thanks for the tip!

**Comment by juanca** [comment]
I'll check it out. Thanks for the tip!

**Comment by juanca** [comment]
It looks like it was not bundled.

screen shot 2017-11-15 at 12 33 52 pm
screen shot 2017-11-15 at 12 33 58 pm

@dignifiedquire Have I missed something?

**Comment by johnjbarton** [comment]
Just to verify: the source does contain the fix, but the 1.7.1 npm release does not.

**Comment by craigkovatch** [comment]
This bug blocks my entire company's migration to React 16. @dignifiedquire any idea when this will be released?

**Pull request merged**
