### PR TITLE
Update Socket.io to 1.7.4 to avoid issue with ws@1.1.2

### PR DESCRIPTION
**Pull request by wehriam**
See https://github.com/karma-runner/karma/issues/2593

### CODE REVIEW

**Comment by wehriam** [comment]
I signed it!

**Comment by wehriam** [comment]
Trying the Google CLA process again...

**Comment by wehriam** [comment]
@creat-or any additional changes required for this to be merged into and released?

**Comment by creat-or** [comment]
Yeah, it has no sense that I approved it, since I have no write privileges on this repository.

**Comment by creat-or** [comment]
Could somebody please review and merge that fix? It's really small and has a lot of impact ;)

**Comment by dignifiedquire** [comment]
The issue why this was not updated before is that there were breaking changes in socket.io before regarding ie7. Does someone have insight into the state of this?

**Comment by creat-or** [comment]
Do you mean this one? https://github.com/socketio/socket.io-client/issues/1099 ... doesn't seem like much activity on this side.

**Comment by wehriam** [comment]
@creat-or I was experiencing https://github.com/karma-runner/karma/issues/2593 which has been resolved by bumping Socket.io to 1.7.4.

**Comment by dignifiedquire** [comment]
Alright I'll take a look at merging things later tonight

**Comment by sujaykathrotia** [comment]
Can we have minor version release with this fixed? I believe a lot of people are having this issue and it would be great to have this fixed in npm instead of patching it manually.

**Comment by dalper01** [comment]
I'd also like a minor release with this. I can patch my dev environment, but my Travis karma tests have been failing and probably will continue to until I can ref a release with this fix.

**Pull request merged**
