### PR TITLE
docs(runner): Add missing link to TeamCity integration page

### PR DESCRIPTION
**Pull request by memark**
Add link to TeamCity integration page. Reorder CI list alphabetically.

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 89e6abc50348cecacbad05beef9f8d921d885eeb
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at http://karma-runner.github.io/0.13/dev/git-commit-msg.html

---
This message was auto-generated by https://gitcop.com

**Comment by memark** [comment]
I signed the CLA. My github username is <memark>.

**Comment by memark** [comment]
Is it even possible to update the commit message? Or do I have to close this PR and create a new one?

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 89e6abc50348cecacbad05beef9f8d921d885eeb
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at http://karma-runner.github.io/0.13/dev/git-commit-msg.html

---
This message was auto-generated by https://gitcop.com

**Comment by memark** [comment]
OK, I think I managed to update the commit message. Please let me know if I need to do anything else.

**Comment by zzo** [comment]
lgtm thanks!

**Comment by Dignifiedquire** [comment]
Thanks :octocat:

**Pull request merged**
