### PR TITLE
Throwing error without loosing stack trace

### PR DESCRIPTION
**Pull request by delfrrr**

### CODE REVIEW

**Comment by dignifiedquire** [comment]
Thanks, that makes a lot of sense, but can you please leave it at using a `for` loop as `forEach` is not available in older browsers.

**Comment by delfrrr** [comment]
Build fails due to https://github.com/karma-runner/karma-requirejs/issues/41

**Comment by delfrrr** [comment]
I will close and reopen PR to trigger travis build

**Comment by dignifiedquire** [comment]
Thanks :octocat:

**Pull request merged**
