### PR TITLE
Engines

### PR DESCRIPTION
**Pull request by stevemao**
continue with #1352

### CODE REVIEW

**Comment by maksimr** [comment]
Oh... seems it [does not work well](https://travis-ci.org/karma-runner/karma/jobs/54700586#L648) with iojs. Possible for iojs this warning not so bad.

Thanks

**LGTM**

**Comment by stevemao** [comment]
I don't understand why it says `"node":"1.5.1"` instead of `"iojs":"1.5.1"`. Should I remove iojs in the engine?

**Comment by Dignifiedquire** [comment]
LGTM

**Comment by mzgol** [comment]
Yes, this still warns:
```
npm WARN engine karma@0.12.31: wanted: {"node":">=0.8 <=0.12","iojs":"~1"} (current: {"node":"1.5.1","npm":"2.7.0"})
```

iojs says `node` because that's what it's been in Node and they don't want to encourage "engine-sniffing". See https://github.com/iojs/io.js/issues/269 for a discussion.

Generally, IMO it should just say:
```
"node":  "~0.8 || ~0.12 || ^1.0"
```
if anything needs to be specified at all. Otherwise io.js users will get warnings indefinitely, making them feel they're in an unsupported scenario.

**Comment by stevemao** [comment]
What happens when node releases 1.5.1? Basically there is no way to tell if it's iojs 1.5.1 or nodejs 1.5.1 then?

**Comment by mzgol** [comment]
> What happens when node releases 1.5.1? Basically there is no way to tell if it's iojs 1.5.1 or nodejs 1.5.1 then?

Yes, although the current thinking is that before Node.js reaches 1.0.0 the projects will reunite. If that doesn't happen then a different solution might be created but judging by the fact io.js seems reluctant to advertise itself as an "engine" it might not add the `iojs` field. Maybe @mikeal/@othiym23/@iarna would know more about plans.

That said, nothing (except maybe Heroku) understands the `iojs` field so adding it is kind of pointless.

**Comment by othiym23** [comment]
@mzgol Your explanation is dead-on, as I understand things. I'm not 100% comfortable with there not being a way to distinguish between Node.js and io.js from the `engines` field, but for now, the only way to tell the difference between the two is to do V8 feature sniffing or to look at the version. I think we're all hoping that the two projects rejoin long before this becomes an issue in practice.

**Comment by stevemao** [comment]
Thanks for explaining this guys. This is just bizarre. 
btw, `jsdom` 4 claims that they only work with `iojs` and they don't actually have an engine field in package.json.

**Comment by iamstarkov** [comment]
iojs released 2.0 version, and I’m getting errors again. fixed it in pr #1394

**Comment by mzgol** [comment]
The `iojs` field is ignored by io.js; I'd rather just remove the field and change `node` to `">=0.8 <=0.12 || >=1"`. @zzo, what do you think?

**Comment by zzo** [comment]
unfortunate but sgtm thanks

**Comment by iamstarkov** [comment]
you are right, iojs don’t care, but npm do

**Comment by iamstarkov** [comment]
Here is a proof from my terminal

    ➜  karma-test git:(master) ✗ n io latest
    ➜  karma-test git:(master) ✗ node -v
    v2.0.0
    ➜  karma-test git:(master) ✗ npm update -g npm
    ➜  karma-test git:(master) ✗ npm -v
    2.9.0
    ➜  karma-test git:(master) ✗ less package.json | grep karma
        "karma": "^0.12.31",
    ➜  karma-test git:(master) ✗ npm i
    npm WARN engine karma-cli@0.0.4: wanted: {"node":"~0.8 || ~0.10"} (current: {"node":"2.0.0","npm":"2.9.0"})
    npm WARN engine karma@0.12.31: wanted: {"node":"~0.8 || ~0.10"} (current: {"node":"2.0.0","npm":"2.9.0"})
    ^C

**Comment by mzgol** [comment]
@iamstarkov `npm` looks at the `node` field, not at the `iojs` field, it's clear from your terminal logs.

**Comment by iamstarkov** [comment]
Wow, you are right, it wasn’t clear for me, and also been confused that karma used to have iojs field. Updated pr

**Pull request merged**
