### PR TITLE
fix(web-server): exit with code 1 when errors loading plugins from co…

### LINKED ISSUE #2141: Fails silently if only reporter is missing
### Expected behavior

If the plugin is missing for the only configured reporter (e.g. karma-mocha-reporter), karma should exit with an error status.
### Actual behavior

It does not run any tests and gives no failure. Only a log warning:

```
17 05 2016 13:28:27.831:WARN [reporter]: Can not load "mocha", it is not registered!
  Perhaps you are missing some plugin?
17 05 2016 13:28:27.851:WARN [karma]: No captured browser, open http://localhost:9876/
17 05 2016 13:28:27.857:INFO [karma]: Karma v0.13.22 server started at http://localhost:9876/
```
### Enviroment Details
- Karma version: 0.13.22

```
module.exports = function(config) {
  config.set({
    frameworks: ['jasmine'],
    reporters: ['mocha'],
    files: ['tests/**/*']
    //...
  });
};
```
### Steps to reproduce the behaviour
1. Create simple project set reporter to `['mocha']`, but do not install the plugin for that reporter
2. `karma start`

### PR DESCRIPTION
**Pull request by ianrufus**
…nfig

replace process.kill with disconnectBrowsers call when loading errors are detected, force test run to exit with code 1 rather than fail silently

Closes #2141

### CODE REVIEW

**Comment by ianrufus** [comment]
I signed it!

**Comment by dignifiedquire** [comment]
Thank you, looks pretty good to me. The only thing I'm concerned about is having no test for ensuring this does what we want. Could you take a look at https://github.com/karma-runner/karma/blob/master/test/unit/server.spec.js and see if you can add a test to check the behaviour of this?

**Comment by ianrufus** [comment]
I've been trying to figure out how to test this, but I'm not getting far...
All I can think of in order to test it would be to extract that behaviour out into an event listener, so that whenever the load_error event is emitted, it errors out.
Don't suppose you can nudge me in the right direction @dignifiedquire? Really want to figure this out :)

**Comment by dignifiedquire** [comment]
Sure thing, so you should be able to utilize the current test setup in `server.spec.js` to this.

This should do the trick probably, not tested it though. 

```js
it('exits with error code 1 on launch errors', (done) => {
  // Make it so that we have load errors
  server.loadErrors =  ['fail']
  // Run the start
  server._start(mockConfig, mockLauncher, null, mockFileList, browserCollection, mockExecutor, doneSpy)
  // Check that the doneSpy was called with the correct code
  expect(doneSpy).to.have.been.calledWith(1)
})
```

**Comment by dignifiedquire** [comment]
@ianrufus ping

**Comment by ianrufus** [comment]
@dignifiedquire Sorry, been distracted with other work!
So far I'm not able to put a test in... I tried your suggestion, but I've been unable to get the doneSpy to be called at all, even with reverting my change. I'm new to sinon, so there's a fair chance I'm doing something wrong.
Only thing I know of to make it testable would be to emit another event, and have that handle disconnecting with code 1, rather than calling disconnectBrowsers directly, but not sure if that's the right approach, or one that you're avoiding with the codebase?

**Comment by Lukinos** [comment]
I have the same problem, and I tried to fix @ianrufus's test, but I 'failed'.
Here what I found:
In order to call the `done(code || 0)` you have to:
   1. Set the variable` webServerCloseTimeout` to 0 in server.js
   1. Add `fileListOnResolve()` after the `server._start` in the @dignifiedquire snippet
Then, when you launch the tests, it will fail by saying `AssertionError: expected spy to have been called at least once, but it was never called`.
However, if I put some hacky `console.log` before and after the `done(code || 0)`, they are all executed.

I think there is some async issue, I tried a lot of thing using the `done` provided by mocha, but nothing seems to work.

**Comment by johnjbarton** [comment]
The current code calls `dieOnError` if there are `loadErrors`, which sets exitCode 1.

**Pull request closed without merging**
