### PR TITLE
feat: bump socket-io to v3 (wip)

### PR DESCRIPTION
**Pull request by muuvmuuv**
BREAKING CHANGE:

Bump socket-io v2 to v3

Closes: #3569

### CODE REVIEW

**Comment by muuvmuuv** [comment]
Would need some help with naming `Type` and `Scope` of the commit messages. Think the bump might be `chore` but should I include the fix in it too? I also thought breaking changes must be prepended with a `!` in before the type.

> https://github.com/karma-runner/karma/blob/ad820a1d0998f0a81eb1d231e3f9b034d8ff21c6/docs/dev/06-git-commit-msg.md

**Comment by muuvmuuv** [comment]
Some tests are locally failing but I really do not know why:

```
7) Scenario: Completion command help # test/e2e/cli.feature:158
   ✔ Before # test/e2e/step_definitions/hooks.js:3
   ✔ When I execute Karma with arguments: "completion --help" # test/e2e/step_definitions/core_steps.js:57
   ✖ Then the stdout is exactly: # test/e2e/step_definitions/core_steps.js:111
       """
       Karma - Spectacular Test Runner for JavaScript.

       COMPLETION - Bash/ZSH completion for karma.

       Installation:
         karma completion >> ~/.bashrc

       Options:
         --help  Print usage and options.                                     [boolean]
       """
       Error: Expected output to be exactly as above, but got:

       Karma - Spectacular Test Runner for JavaScript.

       COMPLETION - Bash/ZSH completion for karma.

       Installation:
         karma completion >> ~/.bashrc

       Optionen:
         --help  Print usage and options.                                     [boolean]
           at World.<anonymous> (/karma/test/e2e/step_definitions/core_steps.js:118:15)
   ✔ After # test/e2e/step_definitions/hooks.js:7
```

Test output seems equal.

**Comment by devoto13** [comment]
"Options" vs "Optionen". Maybe related to your locale?

**Comment by muuvmuuv** [comment]
@devoto13 you are right, I have totally overseen that. Anyway to force my locale or tell the tests they should use "en"?

**Comment by devoto13** [comment]
@muuvmuuv Not sure out of my head, but please send a PR if you figure it out. Ideally force tests to use "en".

**Review by johnjbarton — APPROVED** [review]
Thanks!

**Pull request merged**
