### PR TITLE
fix(common): show more detailed info about error logged in console

### LINKED ISSUE #2854: browser console logs miss vital information
### Expected behaviour
Entire log object is logged by Karma
### Actual behaviour
An unhelpful empty object is logged
image

### Environment Details

- Karma version 1.7.1
- `karma.config.js` file
image

### Steps to reproduce the behaviour

1. Run tests
2. Observe browser error objects are empty

### LINKED ISSUE #2863: Karma console.log or error work differently.
### When 
```Javascript
it('should show error message in Error Object', () => {
  console.log(new Error('This should be displayed'));
});

```
### Expected behaviour
``` bash
LOG: Error: This should be displayed
    at <anonymous>:1:13
    ...
    ...
```
### Actual behaviour
```bash
LOG: TypeError{}
```

### Environment Details

- Karma version (output of `karma --version`):
    "karma": "^1.7.1",
    "karma-chrome-launcher": "^2.2.0",
    "karma-jasmine": "^1.1.0",

- Relevant part of your `karma.config.js` file

#### 1. Write code like below 
```Javascript
it('Error message should be displayed', function() {
  console.log(new Error('This should be displayed'));
});
```

#### 2. run karma test
``` bash
$ karma start
```

#### When you log in normal nodejs app
``` JavaScript
// shouldbe.js
console.log(new TypeError('This should be displayed'));
```

Got this.
```bash
TypeError: This should be displayed
    at Object.<anonymous> (/Users/haseok/workspace/karma-test/expected.js:1:75)
    at Module._compile (module.js:612:30)
    at Object.Module._extensions..js (module.js:623:10)
    at Module.load (module.js:531:32)
    at tryModuleLoad (module.js:494:12)
    at Function.Module._load (module.js:486:3)
    at Function.Module.runMain (module.js:653:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

### PR DESCRIPTION
**Pull request by lusarz**
This closes #2854 and closes #2863

### CODE REVIEW

**Comment by lusarz** [comment]
I wanted to add tests, but I met same problems with run tests like here:
https://github.com/karma-runner/karma/issues/2903#issuecomment-349901235

**Comment by UniverseHan** [comment]
How can it be solved??

**Comment by lusarz** [comment]
@UniverseHan 
I created issue about build problem:
https://github.com/karma-runner/karma/issues/2915

**Comment by dignifiedquire** [comment]
I restarted the build, sad travis was sad

**Comment by lusarz** [comment]
Travis build fixed. 
See problem with AppVeyor, but seems to not be related with this pull request content

**Comment by lusarz** [comment]
@dignifiedquire 
I noticed that AppVeyor fails because it's using master version of useragent (don't know why no one from yarn.lock). I reported this issue in useragent repository:
https://github.com/3rd-Eden/useragent/issues/120

**Comment by lusarz** [comment]
@dignifiedquire any update on AppVeyor build ? It fails on another pull requests as well.

**Comment by dignifiedquire** [comment]
thank you

**Pull request merged**
