### PR TITLE
feat(client): Log global error stack trace

### PR DESCRIPTION
**Pull request by briandipalma**
closes: 2812

### CODE REVIEW

**Comment by briandipalma** [comment]
I signed it!

**Comment by briandipalma** [comment]
Output is changed from

```bash
.../apps/salestrader/src/accountselector UTs in Chrome 60.0.3112 (Mac OS X 10.12.6):  error: true in 127481ms

 Uncaught ReferenceError: j is not defined
at http://localhost:9876/context.html:18 
```

to this

```bash
.../apps/salestrader/src/accountselector UTs in Chrome:  error: true in 9100ms

 Uncaught ReferenceError: j is not defined
at http://localhost:9876/context.html:18:60

ReferenceError: j is not defined
    at eval (eval at <anonymous> (http://localhost:9876/absolute/Users/briand/dev/fe/converted/salestrader/apps/salestrader/node_modules/@caplin/karma-test-runner/dist/entries/uts-test-entry.js?cc7b3bbdb1aa25a9cb61bb06401cfedc8a05761b:4447:1), <anonymous>:18:60)
    at Object.<anonymous> (http://localhost:9876/absolute/Users/briand/dev/fe/converted/salestrader/apps/salestrader/node_modules/@caplin/karma-test-runner/dist/entries/uts-test-entry.js?cc7b3bbdb1aa25a9cb61bb06401cfedc8a05761b:4447:1)
    at __webpack_require__ (http://localhost:9876/absolute/Users/briand/dev/fe/converted/salestrader/apps/salestrader/node_modules/@caplin/karma-test-runner/dist/entries/uts-test-entry.js?cc7b3bbdb1aa25a9cb61bb06401cfedc8a05761b:20:30)
    at eval (eval at <anonymous> (http://localhost:9876/absolute/Users/briand/dev/fe/converted/salestrader/apps/salestrader/node_modules/@caplin/karma-test-runner/dist/entries/uts-test-entry.js?cc7b3bbdb1aa25a9cb61bb06401cfedc8a05761b:10384:1), <anonymous>:8:29)
    at eval (eval at <anonymous> (http://localhost:9876/absolute/Users/briand/dev/fe/converted/salestrader/apps/salestrader/node_modules/@caplin/karma-test-runner/dist/entries/uts-test-entry.js?cc7b3bbdb1aa25a9cb61bb06401cfedc8a05761b:10384:1), <anonymous>:65:3)
    at Object.<anonymous> (http://localhost:9876/absolute/Users/briand/dev/fe/converted/salestrader/apps/salestrader/node_modules/@caplin/karma-test-runner/dist/entries/uts-test-entry.js?cc7b3bbdb1aa25a9cb61bb06401cfedc8a05761b:10384:1)
    at __webpack_require__ (http://localhost:9876/absolute/Users/briand/dev/fe/converted/salestrader/apps/salestrader/node_modules/@caplin/karma-test-runner/dist/entries/uts-test-entry.js?cc7b3bbdb1aa25a9cb61bb06401cfedc8a05761b:20:30)
    at webpackContext (eval at <anonymous> (http://localhost:9876/absolute/Users/briand/dev/fe/converted/salestrader/apps/salestrader/node_modules/@caplin/karma-test-runner/dist/entries/uts-test-entry.js?cc7b3bbdb1aa25a9cb61bb06401cfedc8a05761b:5285:1), <anonymous>:6:9)
    at Array.forEach (<anonymous>)
    at eval (eval at <anonymous> (http://localhost:9876/absolute/Users/briand/dev/fe/converted/salestrader/apps/salestrader/node_modules/@caplin/karma-test-runner/dist/entries/uts-test-entry.js?cc7b3bbdb1aa25a9cb61bb06401cfedc8a05761b:6261:1), <anonymous>:184:21)
```

Which is a slight improvement. I imagine for others it might provide far more useful output.

**Comment by briandipalma** [comment]
Closes #2812

**Comment by Florian-R** [comment]
If this got to merged, could it be made configurable? Sometimes having Karma spit hundred lines of output is not always convenient.

**Comment by briandipalma** [comment]
@Florian-R It's for global syntax errors, their would normally only be one.

From above the function I modified.

```javascript
// error during js file loading (most likely syntax error)
// we are not going to execute at all. `window.onerror` callback.
```

**Comment by briandipalma** [comment]
Why is the CLA taking so long to go green?

**Comment by dignifiedquire** [comment]
Thank you :octocat:

**Pull request merged**
