### PR TITLE
feat(runner): Config option to prevent logging to the console twice

### LINKED ISSUE #2121: Disable or listen to the runner logs
### Expected behavior

I want to be able to disable or listen to the runner logs.
### Actual behavior

All runner logs are written in the standard output as seen [here](https://github.com/karma-runner/karma/blob/master/lib/runner.js#L56)
### Enviroment Details
- Karma version: 3.8.6
### Steps to reproduce the behaviour
1. Create and start a server

``` js
var server = new Server({
    configFile : karmaConfigFile
}, function(exitCode) {
    console.log('Karma has exited with ' + exitCode);
    process.exit(exitCode)
});
server.start();
```
1. On `browsers_ready` `server` event, trigger a run

``` js
server.on('browsers_ready',function () {
    runner.run({ configFile: karmaConfigFile});
});
```
1. See the run output on the console twice, as both the `server` and the `runner` print the output

``` bash
PhantomJS 2.1.1 (Linux 0.0.0): Executed 0 of 1 SUCCESS (0 secs / 0 secs)
PhantomJS 2.1.1 (Linux 0.0.0): Executed 1 of 1 SUCCESS (0.036 secs / 0.001 secs)
```
#### Implement as event

_Preferred_

``` js
var run = runner.run({ configFile: karmaConfigFile});

run.on('data',function(data){
  console.log(data);
});
```
#### Implement flag

``` js
runner.run({ configFile: karmaConfigFile, logs: false});
```
### Notes

This might reflect another issue.
 My `logLevel` is set to `config.LOG_DISABLE` in my karma configuration file. The server seems to not respect the flag when manually triggering the run.

### PR DESCRIPTION
**Pull request by is-already-taken**
This might be the case when Karma.run() is called inside the same
process/terminal as the server is running in (e.g. development
servers).

Fixes #2121, #2799

### CODE REVIEW

**Comment by is-already-taken** [comment]
I signed it!

**Comment by johnjbarton** [comment]
If I understand correctly, you want to prevent output by runner and by reporter?

In general I want to avoid adding yet more and more and more options. This makes our code hard to understand and test.

Why not remove the reporter in the config?
Why not remove the logging in the runner altogether? 
Why not make the logging in the runner based on logLevel setting?

**Comment by is-already-taken** [comment]
> If I understand correctly, you want to prevent output by runner and by reporter?

Correct.

> In general I want to avoid adding yet more and more and more options. This makes our code hard to understand and test.

I understand that.

> Why not remove the reporter in the config?

If you mean removing it from the server's config then there would be no reporting at all since (to my understanding) the runner is just echoing the output of the reporter. That's not feasible. Please clarify.

> Why not remove the logging in the runner altogether?

Can't reliably tell whether this is sarcasm or if I just don't understand. Please clarify.

> Why not make the logging in the runner based on logLevel setting?

I like that one. Would it be acceptable if the runner accepts `logLevel` just like the server and only echoes the reporter results on level `config.LOG_DEBUG`? This means that `logLevel` can be applied in two different places: via the server config / switches and via the runner config / switches. In the runner context this would not configure the runners logger but control the `process.stdout.write()`

I might change the feature this way if you're fine with it.

**Comment by johnjbarton** [comment]
I don't use the 'runner' part; I don't really know how it works.  My suggestion about not logging in the runner is: if the reporter is logging the result why does the runner need to echo that?

To say it another way: was the original feature -- re-log the result in runner -- misdesigned?

**Comment by is-already-taken** [comment]
I think the original idea was, to have the server running in one terminal or even on one host and have the runner connect to that, be it from another terminal or even host. In that case, you want to see the reporter output there. In this context streaming out the reporter results from the socket to the terminal was "good enough". Though I'm not the maintainer, so I'm not 100% sure if that was the idea.

Now, since we're kicking off the runner in same process as the server, they share the same terminal, hence there should be a option to control the runners outputs.

Another approach proposed in the referenced #2121 was to have the runner emit an event. In that case the CLI would have to listen to that event.

**Comment by johnjbarton** [comment]
Can you take a look at the alternative in #2121?

**Comment by is-already-taken** [comment]
A friendly review reminder.

**Pull request merged**
