### PR TITLE
feat(deps): add support for node@8

### LINKED ISSUE #2754: Node 8 Support
### Expected behaviour
I can install and run karma using Node 8
### Actual behaviour
Karma will fail to install because engine support has not included Node 8 yet.

Hi,
First of all thanks for your hard work on this great open source project.

Could you guys please add support for Node 8, and/or give us a timeline for when this change will be released to the public.

### PR DESCRIPTION
**Pull request by kellyjensen**
Add support for nodejs v8.

Updated package.json, .travis.yml, appveyor.yml and installation docs.

Fixes #2754

### CODE REVIEW

**Comment by kellyjensen** [comment]
Thanks @pedrotcaraujo for providing the blueprint for upgrading the supported node version in your PR https://github.com/karma-runner/karma/pull/2571.

**Comment by kellyjensen** [comment]
Try google CLA again.

**Comment by kellyjensen** [comment]
Try google CLA again.

**Comment by shinnn** [comment]
> Try google CLA again.

This doesn't help. The important pont of the @googlebot's comment is:

> If you authored these, maybe you used a different email address in the git commits than was used to sign the CLA (login here to double check)?

**Comment by kellyjensen** [comment]
Would it be better to close this PR and submit a new one ensuring that my email is configured correctly?

**Comment by mgol** [comment]
@kellyjensen it should be enough for you to amend the commit with the correct name & mail:
```
git commit --amend --author="Your Name <your.email@example.com>"
```
and then `git push --force`.

**Comment by kellyjensen** [comment]
Thank you! I will try that.

**Comment by shinnn** [comment]
Thanks to https://github.com/karma-runner/karma/pull/2767, rebasing from the latest `master` will probably fix all failing tests.

**Comment by kellyjensen** [comment]
Yay CI passed!

**Comment by qswitcher** [comment]
+1 this is blocking me from configuring npm with engine-strict enabled.

**Comment by kellyjensen** [comment]
Is there anything else I need to do?  Just checking.

**Comment by shaiksphere** [comment]
Is there an update on this one? This is blocking the usage of `karma` on the Node 8 based projects of ours.

**Comment by dignifiedquire** [comment]
Thank you :octocat:

**Pull request merged**
