### PR TITLE
Assorted link fixes

### PR DESCRIPTION
**Pull request by XhmikosR**
There are plenty more redirected links, but I thought I'd make a first PR with these fixes. :)

I could probably squash the first and the third patch into one if you prefer.

PS1. I'd appreciate if someone could update the build assets for me before merging this. I thought this was automated and there are too many npm vulnerabilities AFAICT to even try to do `npm i`.
PS2. I'm not familiar with the commitlint conventions, so bear with me here
PS3. I personally prefer using `Number.POSITIVE_INFINITY` for concurrency, but I'm not 100% sure on which Node.js versions is supported. It doesn't change the functionality but it's more explicit.

### CODE REVIEW

**Comment by devoto13** [comment]
1. It is automated, the generated website will be updated once the next release is published. So you don't need to worry about it.
2. You can do something like the below to make CI happy:

   docs: fix redirected npmjs links
   docs: change npm to lowercase
   docs: use https when possible

**Comment by XhmikosR** [comment]
Thanks for the hints! That being said, the changes don't affect only the docs. How can I combine more than one component? Maybe `docs,core`?

**Comment by devoto13** [comment]
AFAICT only comments are updated, so it should be fine with just docs scope.

**Comment by devoto13** [comment]
AFAICT only comments are updated, so it should be fine with just docs. Or you can use “docs(core): message” if changes are specific to core.

**Comment by XhmikosR** [comment]
There's one link in code too but I don't think it matters a lot.

**Comment by devoto13** [comment]
> There's one link in code too but I don't think it matters a lot.

Yes.

PS I've amended the last commit to make CI happy.

**Comment by XhmikosR** [comment]
I'd like to keep those links, though. Can't you just update the dist files?

**Comment by devoto13** [comment]
> I'd like to keep those links, though. Can't you just update the dist files?

Unfortunately, we can't do it. Otherwise, we'll have to give up (unnecessarily complicate) a check that bundled client code is up-to-date, which is IMO more important than not having HTTP links.

The right fix would be to change the link in https://github.com/webmodules/dom-serialize, get a release, and update, but the package looks abandoned. Not sure if it worth the trouble.

**Comment by XhmikosR** [comment]
Ah, OK, that makes sense. I wasn't aware that was 3rd-party code. All good then :)

**Comment by XhmikosR** [comment]
BTW the bots are too chatty 😛

**Comment by devoto13** [comment]
> BTW the bots are too chatty 😛

You can block them to avoid any notifications. At least that's what I did 😄

**Review by johnjbarton — APPROVED** [review]
Thanks!

**Pull request merged**
