### PR TITLE
fix: Merge config files on Config.set()

### PR DESCRIPTION
**Pull request by gnail**
The previous implementation overwrote properties so for sub-properties such as Config.client.* they could be overwritten if it's only partially specified.

Works with karma-runner/grunt-karma#194 to solve karma-runner/grunt-karma#165 and other issues mentioned in that PR.

### CODE REVIEW

**Comment by dignifiedquire** [comment]
Thanks. Can you please add a test showing the changed behaviour?

**Comment by gnail** [comment]
Ok I've added a test for the change. The banner is showing the wrong info for some reason though - these are the correct [Travis](https://travis-ci.org/karma-runner/karma/builds/141195720) and [AppVeyor](https://ci.appveyor.com/project/dignifiedquire/karma/build/439/job/i4q08r7kehn4dat0) builds.

**Comment by dignifiedquire** [comment]
Looks good thanks for this. Can you squash all the commits into one please and make the commit message so it follows our [convention](http://karma-runner.github.io/1.0/dev/git-commit-msg.html) then I can merge it thanks :)

**Comment by gnail** [comment]
Ok I've rolled it into one commit (not including the rebase one). Do I need to include the rebase in there?

**Comment by dignifiedquire** [comment]
Thanks :octocat:

**Pull request merged**
