### PR TITLE
fix(config): move puppeteer from dependency to dev-dependency

### LINKED ISSUE #3191: Karma has a non-dev dependency on chromium (via the puppeteer package)
[This commit](https://github.com/karma-runner/karma/commit/0f8b2b17e8fb4aab101ed9acfc65a3090b3298ca?diff=split) added puppeteer (which is a wrapper around headless chrome) as a non-dev dependency of karma. Previously karma had phantomjs-prebuilt as a dev dependency. 

Presumably this change was unintentional? It's a bit annoying because it makes the install of karma take a long time.

### Expected behaviour

Installing karma does not install any particular browser.

### Actual behaviour

Installing karma installs chromium.

### Environment Details

- Karma version (output of `karma --version`): Karma version: 3.1.0
- Relevant part of your `karma.config.js` file: N/A

### Steps to reproduce the behaviour

1. npm install -D karma

### PR DESCRIPTION
**Pull request by johnjbarton**
Fixes #3191
Thanks to @davidshepherd7 for suggesting this.

### CODE REVIEW

**Comment by johnjbarton** [comment]
@lusarz 
This PR looks like it may cause
" Starting browser chrome (linux) on SauceLabs"
to fail.  Could puppeteer cause this?

**Comment by lusarz** [comment]
@johnjbarton Do you have link to CI build where it fails ?

**Comment by johnjbarton** [comment]
I'm unsure what is going on
Here the  pull request #3193 passes
https://travis-ci.org/karma-runner/karma/builds/444825046

Here the release fails
https://travis-ci.org/karma-runner/karma/builds/445228793

The full build history
https://travis-ci.org/karma-runner/karma/builds

**Comment by lusarz** [comment]
@johnjbarton Do you think it may be related with this part of code:
https://github.com/karma-runner/karma/blob/c097ecfecac2b4a2f7998e7b27c5beb99a88fc3b/test/client/karma.conf.js#L65-L69

and different env variables values for pr vs release build ?

**Comment by johnjbarton** [comment]
If we changed that `conf.js` to log the process env values we might get more info and anyway this kind of travis-only config should be logged since it can be so surprising.

**Pull request merged**
