### PR TITLE
fix (client/karma): Set reload context flag to avoid full page reload

### PR DESCRIPTION
**Pull request by FuzzySockets**
...full page reload.

Refer to http://stackoverflow.com/questions/29352578/some-of-your-tests-did-a-full-page-reload-error-when-running-jasmine-tests

and

https://github.com/karma-runner/karma/issues/1101

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 033caad5b125d8f7ae0d09073b3e90403cb8c49b
  * Your subject line is longer than 70 characters
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, test, chore, revert**

Guidelines are available at http://karma-runner.github.io/0.13/dev/git-commit-msg.html

---
This message was auto-generated by https://gitcop.com

**Comment by Dignifiedquire** [comment]
Could you please explain the reasoning behind these changes? (Not saying they are wrong just having a hard time understanding it)

**Comment by FuzzySockets** [comment]
@Dignifiedquire My thoughts are that, anytime "navigateContextTo" gets called (do a search and find instances of invocation), it's a result of the framework purposely changing the context location, either based on an emitted event or otherwise, thus, resulting in an erroneous "Some of your tests did a full page reload!" when it was not a result of a unit test, but rather, an event within the test framework itself.

The 'full page reload' error was getting triggered any time I had excess describe blocks. I'm not sure why the number of describe blocks would affect the number of times this function is called.  Perhaps 'execute' is getting emitted more than once?  I didn't really dig deep enough to see.

**Comment by Dignifiedquire** [comment]
Okay thanks, merging this as it makes sense and hopefully will improve the behaviour for others :)

**Comment by FuzzySockets** [comment]
@Dignifiedquire there is something else going on here.  I'm still seeing the issue after messing with my tests some more.  The suite runs as expected, but when I add any additional describe blocks with just basic expectations, true to be true, for instance, I get the full page reload error.

**Comment by megawac** [comment]
Did this make it into 0.13.12?

**Comment by Dignifiedquire** [comment]
Yes, please test it and give feedback if it works or not

**Comment by megawac** [comment]
We're still receiving the full page reload error in WebKit based browsers with 0.13.12. The tests complete with 392/392 success but fail with the reload error

Reference travis log https://travis-ci.org/jashkenas/backbone/builds/86852035

**Comment by FuzzySockets** [comment]
@megawac I'm still getting it as well in various browsers.  My testing last night must have been a fluke.  I'm going to dig a bit deeper into this today. It's really affecting our ability to write tests.

**Comment by megawac** [comment]
Yeah, it appears to be all webkit based browsers (karma v0.12 still works). I've tested with Chrome + chrome mobile, safari, and opera

**Comment by FuzzySockets** [comment]
@megawac I don't think it's browser specific.  It's happening in PhantomJS for us as well.

**Comment by megawac** [comment]
Isn't phantom also webkit based? I haven't seen this occur with IE, Firefox, Edge, or Opera 11/12

**Comment by FuzzySockets** [comment]
@megawac Yes it is.  Interesting, let me try ours out in Firefox.

**Comment by FuzzySockets** [comment]
@megawac I am getting the issue with firefox as well

**Comment by Dignifiedquire** [comment]
I think the issue is that you need to wait for the iframe to be loaded before you set the reloadingContext to false

**Comment by Dignifiedquire** [comment]
@megawac @FuzzySockets take a look at #1653

**Comment by FuzzySockets** [comment]
@Dignifiedquire This did it!  Good team work sir.

**Comment by FuzzySockets** [comment]
@Dignifiedquire @megawac Added a fix for when iframe is configured to false: https://github.com/karma-runner/karma/pull/1655

**Comment by FuzzySockets** [comment]
Looking into the failed tests.

**Comment by FuzzySockets** [comment]
I'm not getting the failed tests locally, hmm.

**Comment by FuzzySockets** [comment]
Oh I see, there is a PR just before mine:

Pull Request #1654 karma-qunit@0.1.6 breaks build ⚠️
chore(package): update karma-qunit to version 0.1.6

**Comment by FuzzySockets** [comment]
I'm starting to think this issue goes a bit deeper guys.  I'm unable to trigger a full page reload at all now.

**Pull request merged**
