### PR TITLE
fix(reporter): Ensure errors use the source map

### LINKED ISSUE #1495: URL_REGEXP in lib/reporter.js does not match karma-browserify output
Related to #1097, the `URL_REGEXP` in [`karma/lib/reporter.js`](https://github.com/karma-runner/karma/blob/master/lib/reporter.js#L24) fails for karma-browserify.  Karma-browserify spits out urls like this:

> absolute/var/folders/vl/_5jh_5_n3njb7rfcg5tr87p80000gn/T/2316ae91e848b763869f68a80a8e5489.browserify?745c3db05ccd6d7437dca35f2a7b84cdfb23abf1:17133:22

Whereas the expression,

```javascript
var URL_REGEXP = new RegExp('http:\\/\\/[^\\/]*\\/' +
    '(base|absolute)' + // prefix
    '((?:[A-z]\\:)?[^\\?\\s\\:]*)' + // path
    '(\\?\\w*)?' + // sha
    '(\\:(\\d+))?' + // line
    '(\\:(\\d+))?' + // column
    '', 'g')
```

clearly does not match the output. A simple fix that I have tested is to remove the protocol, like this:

```javascript
var URL_REGEXP = new RegExp('\\/' +
    '(base|absolute)' + // prefix
    '((?:[A-z]\\:)?[^\\?\\s\\:]*)' + // path
    '(\\?\\w*)?' + // sha
    '(\\:(\\d+))?' + // line
    '(\\:(\\d+))?' + // column
    '', 'g')
```

I will cross-post an issue with karma-browserify, as the fix may be preferable on their end.

### PR DESCRIPTION
**Pull request by brianmhunt**
Closes #1495

### CODE REVIEW

**Comment by brianmhunt** [comment]
I signed it!

**Comment by brianmhunt** [comment]
The CI error being reported is:

>   1) launchers/base.js restart should start when already finished (crashed):
     Uncaught AssertionError: expected spy to have been called at least once, but it was never called

Which doesn't look like anything I've done, or in any case it's quite beyond me right now how to address it. :)

**Comment by Dignifiedquire** [comment]
> Which doesn't look like anything I've done, or in any case it's quite beyond me right now how to address it. :)

Don't worry about it, some of our tests are a bit sensitive to travis :(

**Comment by Dignifiedquire** [comment]
Could you change the commit message to follow our [convention](http://karma-runner.github.io/0.13/dev/git-commit-msg.html) pleas?

**Comment by brianmhunt** [comment]
@Dignifiedquire Will do, shortly. Sorry for the oversight. Cheers.

**Comment by brianmhunt** [comment]
@Dignifiedquire Test added (and passing) in 7071d0dd72150a87fd26815b879bb3c10721b404; not quite sure if I have the convention renaming down. It may need a rebase, which is beyond me. :grin: If needed, do you mind taking care of the commit naming convention?

Thanks & Cheers

**Comment by Dignifiedquire** [comment]
Thanks, will squash them myself

**Comment by Dignifiedquire** [comment]
Merged as 0407a2280b01972ebcebe9ad341cff87c788975e

**Pull request closed without merging**
