### PR TITLE
feat(config): binpath for custom launchers

### LINKED ISSUE #1737: Add "binpath" parameter for customLaunchers items to override _getCommand
It's required to include Portable Firefox of 20+ with some extensions version into test browsers set. (It is used for some special cases in our client environment).

So i cannot use FIREFOX_BIN env while it's mapped to default instance and i don't want to extend karma-firefox-launcher.

Think it's better to allow override path in config.js:

```
customLaunchers: {
      FFProtable: {
          base: 'Firefox',
          binpath : 'c:/my/special/path/firefox.exe'
      }
  }
```

and with environment variable:

```
customLaunchers: {
      FFProtable: {
          base: 'Firefox',
          binpath : 'env:FFPORTABLE'
      }
  }
```

Have fix it for my own, will prepare pull request.

It's bound to #1738 with it's implementation

### PR DESCRIPTION
**Pull request by comdiv**
Allows explicitly set path to browser binary
both with full OS path or with Environment Variable

Closes #1737

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 6c8e2a23c24e7cbd1aec7efa947bf58afb031226
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at http://karma-runner.github.io/0.13/dev/git-commit-msg.html

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 3588081f855c1169d03aceafcd5850571bfe5236
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at http://karma-runner.github.io/0.13/dev/git-commit-msg.html

---
This message was auto-generated by https://gitcop.com

**Comment by Dignifiedquire** [comment]
Thanks this looks like a nice feature. Could you please add a test for this, so we don't accidentally breaky it later down the line.

**Comment by comdiv** [comment]
Hmm. It's good to add tests but I'm not so familiar with Karma's model and it's injector usage, current Launcher's fixture not meet requirements - where are existed tests of custm*s features?  Or what is best fixture to make them in or get as example?

**Comment by Dignifiedquire** [comment]
There is no specific unit test for `getCommand`, but you can add one in this file: https://github.com/karma-runner/karma/blob/master/test/unit/launchers/process.spec.js

**Comment by comdiv** [comment]
have added one

**Comment by comdiv** [comment]
add test that env variables can be used

**Comment by comdiv** [comment]
Add test you requested, some lint fixes and doc added

**Comment by Dignifiedquire** [comment]
@comdiv need your feedback in the other PR to merge this, as this includes those changes

**Comment by dignifiedquire** [comment]
@comdiv please rebase onto master so I can merge this.

**Comment by maksimr** [comment]
@dignifiedquire I close this PR since it's been two years ago and we don't have similar requests. 👴

**Pull request closed without merging**
