### PR TITLE
fix(docs): fix typos

### PR DESCRIPTION
**Pull request by DarthCharles**
Fixed small typos, nothing to be worried about. :smile:

### CODE REVIEW

**Comment by maksimr** [comment]
LGTM

**Comment by Dignifiedquire** [comment]
Thanks, could you change the commit message to `docs: Fix typos` please, as `fix` is only for actual code change.s

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: a8bcb90a04af3f2063f5e452f7157d31b6df760a
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at http://karma-runner.github.io/0.13/dev/git-commit-msg.html

---
This message was auto-generated by https://gitcop.com

**Comment by DarthCharles** [comment]
Done :octocat: !

**Comment by Dignifiedquire** [comment]
Thanks :octocat:

**Pull request merged**
