### PR TITLE
Make loading assets more understandable

### PR DESCRIPTION
**Pull request by vinnymac**
I created this because of a discussion on Gitter I had with @maksimr 
I ran into this documentation, it left me confused and so I debugged an otherwise simple problem. I tried to be more specific to prevent this from happening to others in the future.

### CODE REVIEW

**Comment by aiboy** [comment]
+1 for that one

**Comment by zzo** [comment]
#merge

**Comment by zzo** [comment]
going to try this again using mary poppins auto-merge - fingers crossed I finally have it set back up

**Comment by zzo** [comment]
#merge

**Comment by btford** [comment]
*crosses fingers*

**Comment by Dignifiedquire** [comment]
As the merge bot is still not running, could you please update your commit message according to our [convention](http://karma-runner.github.io/0.12/dev/git-commit-msg.html) in the meantime, thanks.

**Comment by Dignifiedquire** [comment]
#merge

**Pull request merged**
