### PR TITLE
Feature fix no colors to run command

### PR DESCRIPTION
**Pull request by budde377**
I have not identified and fixed the problem with the 3rd-party reporters not working. The problem was that the reporters didn't update the `USE_COLORS` property, from its default value: `false`. The feature relies highly on this property to be updated and when it wasn't, the reporter would be interpreted as a no-color reporter.

In-order not to break backwards compatibility, a new property was introduced: `EXCLUSIVELY_USE_COLORS` with `undefined` as it's default value. By using this property, the no-colours feature (in the run command) will work for default reporters, i.e. dots and process, and reporters choosing to update the property. 

When fixing this, it became obvious why 3rd-party reporters didn't wan't to update this property: They didn't want to implement two reporters, because this would require for their users to add two reporters to their configuration.

For instance; for the mocha reporter, used in #1894, to implement this feature they would first implement two reporters, say `reporter:mocha` and `reporter:mocha_color`, which would yield a configuration as: 

    reporters: ['mocha', 'mocha_color'] 

where omitting one would disable reporting w/w.o colours, depending on the omitted reporter.

I fixed this in 3294a15 by attempting (silently) to load a "coloured" version of a given reporter. Thus for the mocha reporter to support this feature, all they need to do is implement and export two reporters: `reporter:mocha` and `reporter:mocha_color`. The user-configurations would remain unchanged: I.e.

    reporters: ['mocha'] 

Given a reporter with name `foo` the coloured version must be named `foo_color`, i.e. with postfix `_color`.

### CODE REVIEW

**Comment by dignifiedquire** [comment]
This looks good but just to be sure can you add a e2e test using the mocha reporter that checks for the correct output please?

**Comment by budde377** [comment]
@dignifiedquire Yes, I'll add it this weekend.

**Comment by dignifiedquire** [comment]
@budde377 thanks. Do you want to join the karma maintainer team? Main rules are, keep doing great work like you did, and don't push/merge to `master` on your own.

**Comment by budde377** [comment]
@dignifiedquire Yes, I would very much like that :)

**Comment by dignifiedquire** [comment]
@budde377 done, welcome to the team

**Comment by budde377** [comment]
@dignifiedquire Here you go!

**Comment by dignifiedquire** [comment]
@budde377 this needs a rebase after I merged your other PR

**Comment by budde377** [comment]
@dignifiedquire, Here you go ;)

**Comment by dignifiedquire** [comment]
Thanks. Here goes nothing

**Comment by dignifiedquire** [comment]
Damn. There is another conflict sorry

**Comment by budde377** [comment]
No prop. This should do the trick.

**Pull request merged**
