### PR TITLE
chore(package.json): remove engines field

### PR DESCRIPTION
**Pull request by stevemao**
It warns on iojs and 0.12

### CODE REVIEW

**Comment by maksimr** [comment]
@stevemao Thanks!

We also should [fix documentation](https://github.com/karma-runner/karma/blob/master/docs/intro/01-installation.md) where we describe which version of node we supported.
I prefer explicitly add stable version of node which we supported, instead remove them.(IMHO)

/cc @karma-runner/contributors

**Comment by aymericbeaumet** [comment]
I agree with @maksimr on this. However I find it confusing to mix the node.js and io.js engine versions in such case (`~0.8 || ~0.10 || ~0.12 || ~1`). So @stevemao's solution could actually be the best.

**Comment by Dignifiedquire** [comment]
As we don't support `0.6` or lower we should at least do something like `>= 0.8`.

**Comment by maksimr** [comment]
Can we write something like

```js
"engines": {
  "node":  "~0.8 || ~0.10 || ~0.12",
  "iojs": "~1"
}
```

or

```js
"engines": {
  "node":  ">=0.8 <=0.12",
  "iojs": "~1"
}
```

**Comment by aymericbeaumet** [comment]
[This could be worth a try](https://docs.npmjs.com/files/package.json#engines).

**Comment by stevemao** [comment]
Thanks, before I sent this I looked at many other node projects, many of them removed this field. Some using `>= 0.10` similar to what @Dignifiedquire pointed out. In fact not many support 0.8 any more. I personal like @maksimr 's solution :+1:

**Pull request closed without merging**
