### PR TITLE
Fix minimatch patterns that start with "!"

### PR DESCRIPTION
**Pull request by EzraBrooks**
An attempt to handle #440. Is `config.js` the only place this needs to be handled?

### CODE REVIEW

**Comment by EzraBrooks** [comment]
Should we write a test for this?

**Comment by dignifiedquire** [comment]
> Should we write a test for this?

Yes please, given that that we want to make sure this works as expected in these cases

**Comment by EzraBrooks** [comment]
This is complete, in my opinion, since the tests passed. Unmarking as WIP.

**Comment by EzraBrooks** [comment]
Looks like this might not be cooperating with Windows paths - works fine on macOS on my local machine, but not on AppVeyor. This may be blocked by #251 since the patterns are resolving to absolute paths, correct?

**Comment by EzraBrooks** [comment]
Nevermind, it didn't work on Travis either. Will diagnose when I get a chance.

**Comment by lusarz** [comment]
@EzraBrooks could you rebase it on current master ? Then I'll try to investigate issues with travis

**Comment by johnjbarton** [comment]
Sorry this did not work out. I'm going to close a lot of older pull requests as the source code has changed a lot over the last year.
Thanks!

**Pull request closed without merging**
