### PR TITLE
Update 04-public-api.md

### PR DESCRIPTION
**Pull request by nirmoav**
extracting the config object to a variable creates clarity for the use of the API for users.

### CODE REVIEW

**Comment by nirmoav** [comment]
I signed it!

**Comment by lusarz** [comment]
Thanks, you need to update commit message, because there is check on travis-ci for that. More info here:

https://docs.google.com/document/d/1rk04jEuGfk9kYzfqCuOlPTSJw3hEDZJTBN5E5f1SALo/edit
https://github.com/conventional-changelog-archived-repos/validate-commit-msg

**Comment by nirmoav** [comment]
see PR with a fixed commit message attempt: https://github.com/karma-runner/karma/pull/3084

**Comment by nirmoav** [comment]
hi @lusarz I created a new PR for the doc fix. thanks
#3084

**Pull request closed without merging**
