### PR TITLE
feat: Fail on launcher-, reporter-, plugin-, or preprocessor-load err…

### LINKED ISSUE #855: Throw an error on not found browsers
Currently, it looks like if a browser isn't able to be loaded, karma just warns you and happily proceeds with the browsers that could be loaded.

https://github.com/karma-runner/karma/blob/master/lib/launcher.js#L41-L46

In a CI environment, it would be really, really easy to overlook that all of the sudden one of your configured browsers isn't working anymore, but since no errors are thrown the build is still happy.

I'm proposing that instead of continuing on, encountering a browser that couldn't be loaded should be treated as a fatal error - any loaded browsers should be cleaned up, and the process should exit.

### PR DESCRIPTION
**Pull request by srawlins**
…ors.

Stop karma if a launcher, reporter, plugin, or preprocessor fails to
load, after attempting to load each of them, and reporting errors for
each load error.

Closes #855

### CODE REVIEW

**Comment by srawlins** [comment]
I'm not sure how the authorship worked out... but I grabbed https://github.com/budde377/karma/commit/cd24d954716dcd025fa7141ae0d94fd2c6dc4d26 (authored by me?) and amended with the correct address that Google likes for the CLA. Thanks for the help, @budde377 !!!

**Comment by dignifiedquire** [comment]
Thanks @srawlins @budde377 will review tomorrow :)

**Comment by budde377** [comment]
Don't know how pedantic we need to be wrt. authorship, but after the amend, my name has been removed from the commit (and it now says @srawlins committed by @srawlins). So for the sake of accountability, shouldn't it somehow be evident that the commit is joint work?

**Comment by srawlins** [comment]
Agreed, if you'd like to take the PR again, Christian, feel free. This
commit has my correct email attached, so if you make a PR again, it should
pass the CLA bot.

**Comment by budde377** [comment]
I have successfully done this in #1931.

**Comment by dignifiedquire** [comment]
Closing in favor of #1931

**Pull request closed without merging**
