### PR TITLE
chore: support wallabyjs for karma tests

### PR DESCRIPTION
**Pull request by maksimr**
kww

Thanks @ArtemGovorov for setting up [wallaby](http://wallabyjs.com) in karma.

### CODE REVIEW

**Comment by Dignifiedquire** [comment]
@maksimr is this just so that we can use wallaby or is this actually a user face feature? (If so there should be some docs about this)

**Comment by maksimr** [comment]
@Dignifiedquire just we can use wallaby for development `karma`

**Comment by Dignifiedquire** [comment]
LGTM

**Comment by maksimr** [comment]
#merge

**Pull request merged**
