### PR TITLE
fix(runner): Make process kill timeout configurable

### LINKED ISSUE #2447: <any_browser_here> process gets killed forcibly after 2000 ms
### Expected behaviour
The behaviour as to when to kill the browser should be configurable. There is a hardcoded value in karma/lib/launchers/process.js which is `var killTimeout = 2000`

### Actual behaviour
Since the value is not configurable the browser gets killed after 2s. If there's something running within the browser (e.g. when using karma-coverage and istanbul works on a large number of files), it gets killed.

### Environment Details

- Karma version (output of `karma --version`): 1.3.0
- Relevant part of your `karma.config.js` file: not available

### Steps to reproduce the behaviour

1. Configure karma-coverage to run on a big code base
2. Run karma
3. Observe how the browser gets killed after 2s before it has a chance to finish processing the coverage data

### PR DESCRIPTION
**Pull request by vivganes**
Add a new user configurable property processKillTimeout to set timeout for any spawned process
Closes #2447

### CODE REVIEW

**Comment by wesleycho** [comment]
Is this something that can be tested? I'm not seeing any pre-existing tests around whether it kills it after 2s.

**Comment by vivganes** [comment]
@wesleycho  I was thinking that the existing tests in process.spec.js tested that. I got some tests failing because the value 2000 was not given in my earlier commit.  

I had to add another commit to fix the test cases.

I did not know how to run test cases locally earlier. Now, I know how to run them.  So, will make sure to run them before pushing my commit.

**Comment by wesleycho** [comment]
Ah, I was looking at the wrong area.

This generally looks good to me though approach-wise.

**Comment by vivganes** [comment]
@dignifiedquire Thanks for the suggestion. Just added tests. Can you please check if they look good?

**Comment by dignifiedquire** [comment]
Thank you :octocat:

**Comment by dignifiedquire** [comment]
@vivganes I just realised there was no docs update, could you PR that please, so that the documentation shows this new option?

**Comment by vivganes** [comment]
Sure. I will do that today.

On 18-Jan-2017 10:33 PM, "Friedel Ziegelmayer" <notifications@github.com>
wrote:

@vivganes <https://github.com/vivganes> I just realised there was no docs
update, could you PR that please, so that the documentation shows this new
option?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/karma-runner/karma/pull/2533#issuecomment-273535371>,
or mute the thread

**Pull request merged**
