### PR TITLE
Added support for HTML5 mode 

### PR DESCRIPTION
**Pull request by marthinus-engelbrecht**
Hi, this is a fix for https://github.com/karma-runner/karma/issues/1178. When you activate html5mode in Angular it's a requirement that a `<base>`  tag is present. The fix gives the user the ability to specify whether they want to run the tests in html 5 mode or not.

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 5d38208c7d5efe4d7df82152d59b771e5b256e89
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: f8f4dc5dd1b84dca8bbd27ee82726e2f1a7b61ea
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 53137702891a4dc99a4d7b9cb9a40abb49f014a0
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 7c0e2478b381b7c34baf5c831f66f085bccbf25a
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at http://karma-runner.github.io/0.13/dev/git-commit-msg.html

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: cbf5feef9a1913aaace76eca84e9466dc0549f06
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**
  * Your subject line is longer than 70 characters

Guidelines are available at http://karma-runner.github.io/0.13/dev/git-commit-msg.html

---
This message was auto-generated by https://gitcop.com

**Comment by Dignifiedquire** [comment]
Thanks for the work, but I'm afraid I will not merge this. I don't want to add any more specific framework options, be it angular or another framework. The solution to this is to support custom html files like in #1586 and #488, which would allow you to do something like this for your use case easily.

**Comment by marthinus-engelbrecht** [comment]
:+1: It makes better sense. I commented on another issues and didn't get a response fast enough for the urgency I needed to fix it on my side. Currently pointing at the fork. Will look at the other suggestion, framework agnostic sounds better to me.

**Pull request closed without merging**
