### PR TITLE
feat(constants): export constants

### PR DESCRIPTION
**Pull request by wesleycho**
- Export constants for public usage

This should implement #2361.

### CODE REVIEW

**Comment by maksimr** [comment]
LGTM

**Comment by dignifiedquire** [comment]
Thank you, can you please add documentation for this?

**Comment by wesleycho** [comment]
Where would the best place to add the documentation on the exported constants be? I could add information about some of it to the configuration file docs, but it seems out of place for some of the values such as `DEFAULT_PORT` and `DEFAULT_HOSTNAME`.

**Comment by dignifiedquire** [comment]
https://github.com/karma-runner/karma/blob/master/docs/dev/04-public-api.md < public api is the place to put it I would say

**Comment by wesleycho** [comment]
Added docs there for all of the constants

**Pull request merged**
