### PR TITLE
feat(web-server): Serve all files under urlRoot

### PR DESCRIPTION
**Pull request by nmalaguti**
Serves all files under urlRoot.

### CODE REVIEW

**Comment by nmalaguti** [comment]
The coverage failures don't appear to be due to theses changes, but rather the result of the latest version of karma-coverage (0.3.1). Coverage passes when using karma-coverage 0.2.x.

**Comment by nmalaguti** [comment]
It's possible this change is insufficient to accomplish the TODO that @vojtajina created.

I believe this change is valuable because when using a proxy in front of karma, setting a urlRoot causes the html page to be served up correctly, but none of the assets are served under the urlRoot.

This prepends all asset paths with urlRoot when they are added to the html and serves up the proper files when requested.

**Comment by nmalaguti** [comment]
Can someone review/give feedback on this change so I can improve it or it can be merged?

Thanks.

**Comment by Dignifiedquire** [comment]
Could you rebase onto the latest master please? 
In general I like the way this is going, but I will do a closer review in the next days

**Comment by nmalaguti** [comment]
@Dignifiedquire rebased.

**Comment by nmalaguti** [comment]
@Dignifiedquire is this ready to be merged?

**Comment by Dignifiedquire** [comment]
Merged into canary as 4a0a152bd912b653167b9c0cca00d896b49acc94

**Pull request closed without merging**
