### PR TITLE
feat: add isDebug flag to karma client

### PR DESCRIPTION
**Pull request by jquense**
That way test adapters and plugins can properly adapt behavior based on the context like karma does, e.g. customizing console logging

### CODE REVIEW

**Comment by johnjbarton** [comment]
Please expand on the use-case for this feature.

The PR doesn't have any logic or tests yet.

**Comment by jquense** [comment]
Not sure what test you'd like here, but happy to add one. 

Karma has different behavior in debug mode vs its normal run mode, but test frameworks and adapters aren't able to tell which mode they are in. In our specific case, in `karma-jest` we are handling the serialization of `console.*` calls on the client and handling them ourselves in a reporter, without a flag though I can't tell whether I need to to proxy the native `console` calls or let them go through.

**Comment by johnjbarton** [comment]
> Karma has different behavior in debug mode

Can you test if the URL contains `debug.html`?

**Comment by jquense** [comment]
> Can you test if the URL contains debug.html? 

in some cases, but only works if tests don't change the url via the history api. Personally this happens a lot in our test suites in SPA applications.

**Comment by johnjbarton** [comment]
Ok, so a test would verify that the flag existed in the loaded debug.html. That test would prevent someone from deleting line.

**Comment by jginsburgn** [comment]
@jquense Please add the requested test :)

**Comment by jquense** [comment]
hi @jginsburgn unfortunately i don't have the time to jump back into this. sorry for the drive by PR without a test, feel free to close it. thanks!

**Comment by jginsburgn** [comment]
Gotcha! I will close for now. Thanks for the update.

**Pull request closed without merging**
