### PR TITLE
chore: remove support for node 6

### PR DESCRIPTION
**Pull request by lusarz**
This pull request remove support for node v6.

Let me know if I missed something here ...

### CODE REVIEW

**Comment by lusarz** [comment]
@johnjbarton Thank you, I've updated commit message. 

What you mean by "integration-tests project" ?

**Comment by johnjbarton** [comment]
The karma-runner integration tests (tests with plugins) are  configured here:
https://github.com/karma-runner/integration-tests/blob/master/.travis.yml
and pulled into the test run via 
https://github.com/karma-runner/karma/blob/master/scripts/integration-tests.sh

**Comment by lusarz** [comment]
I created pull request on integration-tests project:
https://github.com/karma-runner/integration-tests/pull/10

Yeah, it would be nice to update this documentation line - do you have proposition for whole section ? Because currently it contains `Karma works on all LTS versions `, which would not be true after this pull request merge.

**Comment by lusarz** [comment]
Okay, I updated this info in docs.

**Pull request merged**
