### PR TITLE
meta viewport added to static html head

### PR DESCRIPTION
**Pull request by andykenward**
so you can test media queries need meta tag added in the static html files

### CODE REVIEW

**Comment by andykenward** [comment]
I signed it!

**Comment by Dignifiedquire** [comment]
Hey, thanks for your contribution, could you please update your commit message to follow our [convention](http://karma-runner.github.io/0.12/dev/git-commit-msg.html)? 

Also does this imply any issues for people not using those queries?

**Comment by unional** [comment]
I want the same thing. As for the convention, does this consider as `fest` or `fix`?

**Comment by Dignifiedquire** [comment]
Closing in favor of #1543

**Pull request closed without merging**
