### PR TITLE
IGNORE

### PR DESCRIPTION
**Pull request by zzo**
try to add g++ dep for travis

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 1a2c5bcbc5a93a08e6eff2095e5cbc195e6517a4
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at http://karma-runner.github.io/0.13/dev/git-commit-msg.html

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 1a2c5bcbc5a93a08e6eff2095e5cbc195e6517a4
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 6e558529dc2c631ee8fb8718dfc05430a44fc90f
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at http://karma-runner.github.io/0.13/dev/git-commit-msg.html

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 1a2c5bcbc5a93a08e6eff2095e5cbc195e6517a4
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 6e558529dc2c631ee8fb8718dfc05430a44fc90f
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 0b90600763c305c0591363528576bf953de27bd6
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at http://karma-runner.github.io/0.13/dev/git-commit-msg.html

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 1a2c5bcbc5a93a08e6eff2095e5cbc195e6517a4
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 6e558529dc2c631ee8fb8718dfc05430a44fc90f
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 0b90600763c305c0591363528576bf953de27bd6
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: c025c1d9977ed3b38f4aa3f5f138bbf02fd747d3
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at http://karma-runner.github.io/0.13/dev/git-commit-msg.html

---
This message was auto-generated by https://gitcop.com

**Comment by mzgol** [comment]
This PR is irrelevant now after #1672, it can be closed.

**Pull request closed without merging**
