### PR TITLE
fix(client): revert modern syntax to allow IE11 use

### PR DESCRIPTION
**Pull request by johnjbarton**
Fixes #3629 #3630

### CODE REVIEW

**Comment by johnjbarton** [comment]
@longlho FYI

**Comment by longlho** [comment]
hmm also the arrow functions need to be rewritten as well :(

**Comment by devoto13** [comment]
I also don't see this fixing anything, which was not fixed in #3629. Or am I missing something?

**Comment by johnjbarton** [comment]
No, I missed the later commits that fixed updater.js, sorry.

**Comment by XhmikosR** [comment]
@johnjbarton @devoto13 Shouldn't you all enforce this with ESLint? BTW I personally dislike standard, but you could use standardx to enforce some options.

**Comment by devoto13** [comment]
@XhmikosR This sounds like a great idea! I'll look into setting up ESLint to fail on >ES5 code in the client scripts. This way we can catch such problems before IE 11 tests are run on the post-commit build.

**Comment by johnjbarton** [comment]
The IE11 `test:client` is clearly adequate to this task, if we run that test. The fail here was that the browserstack tests failed on post commit and we did not block the PR commit for the new syntax.  The fix is should be to run the test and have it block PRs from merging.

**Comment by XhmikosR** [comment]
I still think it's just simpler to enforce ES5 in the linting stage, but it's just my 2 cents.

**Pull request closed without merging**
