### PR TITLE
README: changed 0.12 links -> 0.13 versions

### PR DESCRIPTION
**Pull request by sirhodes**

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: a7c168171b69d768b45a3150b8c60c98ae50a378
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**
  * Your subject line is longer than 70 characters

Guidelines are available at http://karma-runner.github.io/0.13/dev/git-commit-msg.html

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: a7c168171b69d768b45a3150b8c60c98ae50a378
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**
  * Your subject line is longer than 70 characters

 * Commit: a8193da727057a641d07e9213371d27b4a56312d
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at http://karma-runner.github.io/0.13/dev/git-commit-msg.html

---
This message was auto-generated by https://gitcop.com

**Comment by sirhodes** [comment]
I signed the CLA.

**Comment by sirhodes** [comment]
Do I need to rebase the commit that I've already submitted in order to be merged?

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 0cb746968483d4259e3ac0628785cb0474acc523
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: b1ab4c0739427d7f2d9fa2919188b8a78561ae49
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at http://karma-runner.github.io/0.13/dev/git-commit-msg.html

---
This message was auto-generated by https://gitcop.com

**Comment by Dignifiedquire** [comment]
Commits are now fine. I added a url `/latest` so this does not need to be updated on every new release. Could you use that please. Thanks a lot :)

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 0cb746968483d4259e3ac0628785cb0474acc523
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: b1ab4c0739427d7f2d9fa2919188b8a78561ae49
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: f1b8f94a2e91ecba2a301533c6433511c0b0ec72
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at http://karma-runner.github.io/0.13/dev/git-commit-msg.html

---
This message was auto-generated by https://gitcop.com

**Comment by sirhodes** [comment]
@Dignifiedquire updated to new url!

**Comment by Dignifiedquire** [comment]
Thanks, one more thing  could you squash all the three commits into one please?

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: a239cd02672a063fda24a0e916559344943eb133
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at http://karma-runner.github.io/0.13/dev/git-commit-msg.html

---
This message was auto-generated by https://gitcop.com

**Comment by sirhodes** [comment]
@Dignifiedquire done!

**Pull request merged**
