### PR TITLE
Convert to ts

### PR DESCRIPTION
**Pull request by luisvt**

### CODE REVIEW

**Comment by Florian-R** [comment]
@luisvt Has this been discussed before? Can't find a ticket for this. (FWIW, I don't think this pull is a good idea)

**Comment by luisvt** [comment]
No, it hasn't been discussed before. Right now it does not have any big change from JavaScript. However, this opens a big opportunity to add more types to the code. Furthermore, with future changes we could refactor code easily. 

There is one test that fails in Travis, and I don't know why. When I run it locally it doesn't fails.

**Comment by dignifiedquire** [comment]
@luisvt thank you for the big effort. I have been thinking about moving this project to a typed JavaScript variant (TypeScript or Flow) but have not decided yet. 

The major thing holding me back at this point is that it would make it harder for others to contribute, which I would like to avoid, especially as most new code and fixes at the moment come from the community.

**Comment by luisvt** [comment]
From what I know:
* `flow` = `es6` + `types`
* `ts` = `es6` + `types` + `private` + `other feat.`.
* From previous we can say that: `ts` = `flow` + `types` + `other feat`

I chose to migrate the code to Typescript because it is more flexible and has more features than `es6` and `flow`.

And Yes, `ts` or any other language will add one more step to development cycle (transpile the code). In the case of Typescript we could solve this adding a `tsc` task in grunt or any other task runner.

**Comment by maksimr** [comment]
I also think move on TypeScript or other languages which should be compiled to javascript is not good idea because:

- Our target platform nodejs(JavaScript)
- Yet another point of failure
- Add compilation step
- Require infrastructure around this language
- Require additional knowledge | Community (see @dignifiedquire  comment above) 
- Language compiled to javascript can be abandoned

So we should carefully look at pros and cons which provide this language.
IMHO I would wait ES6 - which new standart for JavaScript.

**Comment by dignifiedquire** [comment]
I've been testing out using flowtype, which I personally like more in this branch if someone wants to check it out: https://github.com/karma-runner/karma/tree/flow

**Comment by ywonglanecove** [comment]
This project is all about unit testing and it makes TDD in JavaScript much more enjoyable

With TDD you get 100% coverage, with 100% coverage you have made sure every single function behaves correctly, why would you need to spend extra time to make sure it uses the correct types?

**Comment by johnjbarton** [comment]
We are still pursuing ES6 level code, we can reevaluate TS once we get there.

**Pull request closed without merging**
