### PR TITLE
chore(ci): remove more old connection security stuffs

### PR DESCRIPTION
**Pull request by johnjbarton**

### CODE REVIEW

**Comment by devoto13** [comment]
@johnjbarton Nice! Let's see if this solves SauceLabs error on master.

**Comment by devoto13** [comment]
@johnjbarton I had a PR to update the check in integration-tests repo: https://github.com/karma-runner/integration-tests/pull/11/files. But I think now it is better to use something similar to what you do in https://github.com/karma-runner/karma/pull/3461/files. Will update the PR soon.

**Comment by devoto13** [comment]
@johnjbarton After some digging it seems that the problem is [this line](https://github.com/karma-runner/karma/blob/debug-sauce-labs/.travis.yml#L24). My theory is that https://github.com/karma-runner/integration-tests/tree/master/saucelabs test tries to start Sauce Connect proxy, but fails because it is already started by Travis itself. Can't check it though, because SAUCE_* variables are only available to the `master` branch and I can't access them in my [debugging branch](https://travis-ci.org/github/karma-runner/karma/jobs/672712683#L247).

**Comment by johnjbarton** [comment]
I think the integration-tests are installed in the `karma-runner/karma` travis session so I don't *think* that .travis.yml is read.  But your theory about the sauce connect could still be right, I just added that line as a guess. I "unguessed" and I updated the integration_tests travis file also, thanks.

**Pull request merged**
