### PR TITLE
feat(config): Allow custom context and debug files

### PR DESCRIPTION
**Pull request by ernsheong**
Continuation of https://github.com/karma-runner/karma/pull/1586 and https://github.com/karma-runner/karma/pull/1360

Potential progress/fix for https://github.com/karma-runner/karma/issues/1752

### CODE REVIEW

**Comment by ernsheong** [comment]
I signed it!

**Comment by Dignifiedquire** [comment]
Thanks, this looks pretty good but we need a test to ensure this works as expected. Could you take a look at the e2e tests and create one that uses a custom one and just test that is used

**Comment by ernsheong** [comment]
```
Running "test:client" (test) task
Running /Users/ernsheong/Repositories/karma/bin/karma start test/client/karma.conf.js --single-run --no-auto-watch --reporters=dots
failed to add custom browserify preprocessor
{ [Error: Cannot find module 'karma/lib/preprocessor'] code: 'MODULE_NOT_FOUND' }
25 01 2016 22:41:14.225:INFO [karma]: Karma v0.13.19 server started at http://localhost:9876/
25 01 2016 22:41:14.230:INFO [launcher]: Starting browser Chrome
25 01 2016 22:41:15.261:INFO [Chrome 47.0.2526 (Mac OS X 10.11.2)]: Connected on socket /#AWU-3m1tjAEk3GmEAAAA with id 5905339
Chrome 47.0.2526 (Mac OS X 10.11.2) ERROR
  Uncaught ReferenceError: require is not defined
  at /Users/ernsheong/Repositories/karma/test/client/karma.spec.js:1
Chrome 47.0.2526 (Mac OS X 10.11.2): Executed 0 of 0 ERROR (0.066 secs / 0 secs)
[Error: failed to add custom browserify preprocessor
{ [Error: Cannot find module 'karma/lib/preprocessor'] code: 'MODULE_NOT_FOUND' }]
Fatal error: Client unit tests failed.
```
Hi @Dignifiedquire, I will try to do that. Firstly though, can you help me with the above error message? I'm basically just trying to run `grunt` locally to make sure tests pass locally but they don't :(

**Comment by Dignifiedquire** [comment]
Make sure you run this before

```bash
  $ npm install
  $ rm -rf node_modules/karma
  $ cd node_modules
  $ ln -s ../ karma
  $ cd ../
  $ grunt browserify
  ```

**Comment by dignifiedquire** [comment]
@ernsheong ping

**Comment by ernsheong** [comment]
@dignifiedquire Hi sorry for the delay. Can you teach me how to debug within PhantomJS? Or better still, how can I use the Chrome debugger to debug the feature test?

**Comment by dignifiedquire** [comment]
You can specify temporary to use Chrome in the feature test like this: https://github.com/karma-runner/karma/blob/master/test/e2e/basic.feature#L23-L38

**Comment by ernsheong** [comment]
Sorry, I'm stuck. (not a Node guy, more front end). How can I debug the `lib/config.js`, or the karma.js middleware file. The browser does not have that JS file loaded within it.

**Comment by dignifiedquire** [comment]
@ernsheong all code in `/lib` is run in node, and all code in `/client` is run in the browser. What exactly are you trying to debug? You can try just adding `console.log` statements in `lib/config.js` if you need to check simple things.

**Comment by ernsheong** [comment]
Most of the path resolution and logic happens on the Node side. Something is not wired up right as I am unable to get the test to pass. Another eye would be helpful.

**Comment by fredericoschardong** [comment]
@ernsheong I made a PR to your repository with the changes needed to pass the test. I am having some issues with PhantomJS on my machine and was only able to test my changes using Chrome. Please let me know if they don't work.

**Comment by ernsheong** [comment]
@dignifiedquire I finally got it to work! There was some weirdness for the cucumber mocha test, but I found a way to make it work...

**Comment by dignifiedquire** [comment]
Thanks a lot!

**Pull request merged**
