### PR TITLE
style: small spelling fix

### PR DESCRIPTION
**Pull request by DarthCharles**
Small typos I encountered while checking the code. Hope it helps :)

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 343e64d3d9ce290ccf4839e04051a66c1b2bd4b6
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at http://karma-runner.github.io/0.13/dev/git-commit-msg.html

---
This message was auto-generated by https://gitcop.com

**Comment by Dignifiedquire** [comment]
Thanks, the bot was referring to the commit message itself though, not the title of the PR. You can change that by using either `git amend` or `git rebase -i`, see [here](https://www.atlassian.com/git/tutorials/rewriting-history/git-commit--amend/) for details

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 343e64d3d9ce290ccf4839e04051a66c1b2bd4b6
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: bd3e214935d61dfd1aaf896c972a1169ba9c71ce
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 83df51d97ded6b554bc8e94d39315103de56ac73
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**
  * Your subject line is longer than 70 characters

Guidelines are available at http://karma-runner.github.io/0.13/dev/git-commit-msg.html

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 343e64d3d9ce290ccf4839e04051a66c1b2bd4b6
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: bd3e214935d61dfd1aaf896c972a1169ba9c71ce
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 83df51d97ded6b554bc8e94d39315103de56ac73
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**
  * Your subject line is longer than 70 characters

 * Commit: ea5905314704903e567c38d8a4afd9eb7335137a
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: ddcd3b43078056fbdd7c181e81142e8cf8bca9e1
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**
  * Your subject line is longer than 70 characters

Guidelines are available at http://karma-runner.github.io/0.13/dev/git-commit-msg.html

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: f30bf970b157de5133e28795e0bde315a125a8a1
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at http://karma-runner.github.io/0.13/dev/git-commit-msg.html

---
This message was auto-generated by https://gitcop.com

**Comment by DarthCharles** [comment]
@Dignifiedquire I think I'm messing things up here.

**Comment by Dignifiedquire** [comment]
All good now thanks, the bot is not too clever ;)

**Comment by Dignifiedquire** [comment]
:octocat:

**Pull request merged**
