### PR TITLE
relax node and iojs restrictions

### PR DESCRIPTION
**Pull request by nmccready**
Trying to get rid of warnings. Related to https://github.com/karma-runner/karma-cli/pull/10 .

### CODE REVIEW

**Comment by nmccready** [comment]
CLA was signed

**Comment by Dignifiedquire** [comment]
Thanks for the contribution! Could you explain in more detail what warnings you are getting and why you are reintroducing the `iojs` field (The last conversation about this that I read was that this shouldn't be used and npm would ignore it)

**Comment by nmccready** [comment]
```
npm WARN engine karma@0.0.4: wanted: {"node":"~0.8 || ~0.10"} (current: {"node":"0.12.4","npm":"2.11.0"})
```

**Comment by Dignifiedquire** [comment]
These changes here shouldn't be needed, see my comment on the other PR.

**Pull request closed without merging**
