### PR TITLE
[WIP] No more coffeescript

### PR DESCRIPTION
**Pull request by Dignifiedquire**
Start introducing babel into the code base (tests) in favor of coffeescript

### CODE REVIEW

**Comment by kahwee** [comment]
How can I help in this?

**Comment by Dignifiedquire** [comment]
@kahwee The main thing left to do is review all tests the generated javascript is readable, fix linting and running the tests (only one failure atm).  
If you do so please open an informal PR against this branch with your changes.

**Comment by kahwee** [comment]
I've signed the CLA

**Comment by kahwee** [comment]
@Dignifiedquire I like some help on `test:client`. I'm not sure how `grunt test:client` works:

Somehow it can't connect to my client this way:

```
karma - fix-mocha-test ❯ grunt test:client
Running "test:client" (test) task
Running /Users/kahwee/projects/karma/bin/karma start test/client/karma.conf.js --single-run --no-auto-watch --reporters=dots
25 07 2015 12:34:51.823:INFO [framework.browserify]: 472453 bytes written (0.80 seconds)
25 07 2015 12:34:51.828:INFO [framework.browserify]: bundle built
25 07 2015 12:34:51.833:INFO [karma]: Karma v0.13.2 server started at http://localhost:9876/
25 07 2015 12:34:51.839:INFO [launcher]: Starting browser Chrome
25 07 2015 12:34:53.794:WARN [web-server]: 404: /Users/kahwee/projects/karma/static/karma.js
25 07 2015 12:35:11.841:WARN [launcher]: Chrome have not captured in 20000 ms, killing.
25 07 2015 12:35:12.004:INFO [launcher]: Trying to start Chrome again (1/2).
25 07 2015 12:35:13.298:WARN [web-server]: 404: /Users/kahwee/projects/karma/static/karma.js
```

However, if I were to run using the command `karma start test/client/karma.conf.js --single-run --no-auto-watch --reporters=dots`, it works.

```
karma - fix-mocha-test ❯ karma start test/client/karma.conf.js --single-run --no-auto-watch --reporters=dots
25 07 2015 12:35:41.953:INFO [framework.browserify]: 472453 bytes written (0.79 seconds)
25 07 2015 12:35:41.957:INFO [framework.browserify]: bundle built
25 07 2015 12:35:41.962:INFO [karma]: Karma v0.13.3 server started at http://localhost:9876/
25 07 2015 12:35:41.966:INFO [launcher]: Starting browser Chrome
25 07 2015 12:35:43.529:INFO [Chrome 44.0.2403 (Mac OS X 10.10.4)]: Connected on socket mKMAqPUQhyltVGNPAAAA with id 74311639
............................
Chrome 44.0.2403 (Mac OS X 10.10.4): Executed 28 of 28 SUCCESS (0.242 secs / 0.061 secs)
```

Does this count as a pass or fail?

**Pull request merged**
