### PR TITLE
Minor Spelling Error in Docs

### PR DESCRIPTION
**Pull request by RickCarlino**
Found two typos in the docs. This is PR is gigantic, I know.

### CODE REVIEW

**Comment by RickCarlino** [comment]
I signed it!

**Comment by dignifiedquire** [comment]
Thanks, could you please change the commit message to follow our [convention](http://karma-runner.github.io/0.13/dev/git-commit-msg.html)

**Comment by Moumi** [comment]
The spelling error seems to have been fixed in another PR ( #1943 ). This PR should be closed. :+1:

**Comment by dignifiedquire** [comment]
Thanks two both of you !

**Pull request closed without merging**
