### PR TITLE
Added AppVeyor integration

### PR DESCRIPTION
**Pull request by twolfson**
In #2001, we discussed and decided to add an AppVeyor integration to catch Windows errors before they are landed. In this PR:

- Added AppVeyor integration
- Added AppVeyor badge to README

**Passing build:** https://ci.appveyor.com/project/twolfson/karma/build/16

For lots of helpful Windows pointers, see the thread in #2001.

**Notes:**

This build will initially fail due to #2001 (i.e. we don't properly handle no `customContextFile` on Windows).

### CODE REVIEW

**Comment by twolfson** [comment]
Notes for @dignifiedquire on how to enable AppVeyor for this project

1. Visit http://www.appveyor.com/
2. Click "Sign In" in the upper right and complete sign in
3. We should arrive on https://ci.appveyor.com/projects . If not, go there
4. Click "+ New Project" in upper left
5. Wait for sync to complete
6. Find `karma` in the list
7. Hover the item and click "+ Add" on the right side of the line
    - The project is now enabled :tada:
8. Perform a `git push` to trigger a new build (I think "New Build" might work) to verify everything works as expected
    - Reminder that `master` will fail until #2001 is landed

**Comment by dignifiedquire** [comment]
Merged manually. Thanks

**Comment by dignifiedquire** [comment]
Looks like it's not happy though https://ci.appveyor.com/project/dignifiedquire/karma/history

**Comment by twolfson** [comment]
During development, I was exclusively testing against Node.js@5.0. In my haste, I tried to sneak in `0.10`, `0.12`, and `4`. I dropped `0.10` from AppVeyor after getting `npm` errors and not being able to figure out PowerShell in their YAML, then went to sleep.

It looks like we might have to drop more versions of Node.js =(

**Comment by twolfson** [comment]
Got `Node@0.12` and `Node.js@4` passing via an `npm` upgrade. I guess it shrinks the size of `xcopy`

https://ci.appveyor.com/project/twolfson/karma/build/25

**Comment by twolfson** [comment]
Also, I found the cause of my symlink errors in my VM. It turns out Windows dislikes creating symlinks on a shared drive =(

**Comment by twolfson** [comment]
Added some silencing for `xcopy` since scrolling is really annoying:

https://ci.appveyor.com/project/twolfson/karma/build/26/job/sufo0nabs6a95ptt

**Comment by twolfson** [comment]
Huh, we have some failing tests in Node.js@0.10 on Windows:

https://ci.appveyor.com/project/twolfson/karma/build/27/job/ptju2v60t4ikasg3

**Comment by twolfson** [comment]
It turns out I got the symlink wrong the first time so it was linking `node_modules/karma` to `./` (i.e. `node_modules`). It's been resolved now:

https://ci.appveyor.com/project/twolfson/karma/build/28/job/5sbk5jm00f3hcoag

**Pull request closed without merging**
