### PR TITLE
chore: Move to standard JS style.

### PR DESCRIPTION
**Pull request by Dignifiedquire**
Make life as a developer a little easier. For more info see
https://github.com/feross/standard.

### CODE REVIEW

**Comment by Dignifiedquire** [comment]
Ref #1417

**Comment by Dignifiedquire** [comment]
@maksimr could you let your eyes rest on this for a moment when you have some time please?

**Comment by maksimr** [comment]
@Dignifiedquire 

wow remove semicolon ... strongly :)

**Comment by Dignifiedquire** [comment]
> wow remove semicolon ... strongly :)

I like to save my sanity :)

**Comment by luisrudge** [comment]
:+1:

**Comment by Dignifiedquire** [comment]
I signed it!

**Comment by Dignifiedquire** [comment]
so @maksimr you think we can merge this? :)

**Comment by maksimr** [comment]
@Dignifiedquire LGTM

**Comment by Dignifiedquire** [comment]
@maksimr one more view, I forgot to do the test files :)

**Comment by maksimr** [comment]
@Dignifiedquire :+1:

**Pull request merged**
