### PR TITLE
fix(client): dynamic protocol for socket.io

### LINKED ISSUE #1400: Hardcoded http protocol for socket.io
`http` protocol is hardcoded in karma.js [here](https://github.com/karma-runner/karma/blob/master/client/main.js#L10) at the moment. This means that Karma does not work in an environment where `http` is not used (only `https`).

Karma can check `window.location.protocol` instead, which will allow to run it in `https`-only environments.

### PR DESCRIPTION
**Pull request by clexit**
Look up location.protocol for socket.io,
in order to use Karma in https-only enviournment

Closes #1400

### CODE REVIEW

**Comment by maksimr** [comment]
@clexit Thanks!

Are you use https proxy? 
Because karma run http server.

**Comment by clexit** [comment]
Hi @maksimr!

Yes, it's https that proxies to the local Karma instance. Since there is only https, socket.io fails to connect because of the hardcoded protocol (it tries to connect from https to the inexistent http). While local http Karma is ok, we cannot configure http proxy due to security restrictions.

Can this change be merged? I've just noticed that the <scope> tag in the commit message might be incorrect. Does it matter for merge?

**Comment by maksimr** [comment]
@clexit 

> Can this change be merged?
Yes, I think it's good change!

>  I've just noticed that the tag in the commit message might be incorrect. Does it matter for merge?
What tag? cli?

I think will be better change **scope** to `client`, because `cli` usual mean command line interface

`fix(client): ...`

Thanks

**Comment by clexit** [comment]
Cool, thanks!

I changed the *scope* tag to `client`. The history should be OK now.

**Comment by maksimr** [comment]
@clexit Thanks

**LGTM**

**Comment by Dignifiedquire** [comment]
LGTM

**Comment by maksimr** [comment]
#merge

**Comment by maksimr** [comment]
#merge

**Comment by zzo** [comment]
#merge

**Comment by Dignifiedquire** [comment]
#merge

**Pull request merged**
