### PR TITLE
feat(config): add appendsha option for files

### LINKED ISSUE #2756: Request: config option to not append file
### Environment Details

- Karma version (output of `karma --version`):
- Relevant part of your `karma.config.js` file

### Steps to reproduce the behaviour

1.
2.
3.

### PR DESCRIPTION
**Pull request by JohnRiv**
This allows users to prevent the file SHA query string from being added to included files by specifying 'appendsha: false'. This is to prevent files from being loaded twice, which can occur if a file is included by Karma and then later referenced by another file in the code (such as an HTML import)

Follow-up to #2760 

Closes #2756

### CODE REVIEW

**Comment by johnjbarton** [comment]
> This is to prevent files from being loaded twice, which can occur if a file is included by Karma and then later referenced by another file in the code (such as an HTML import)

Hmm.  I don't see how removing the sha from the URL accomplishes that goal.  

Duplicate inclusion sounds like a bug, possibly just related to poor configuration analysis.  

Can you explain more about that issue>

**Comment by JohnRiv** [comment]
So, my need was for HTML Imports, which unfortunately aren't going to be a thing anymore. 

@mario-d-s can you provide some insight into how you felt this could help out your use case?

**Comment by mario-d-s** [comment]
@JohnRiv for us this gave trouble where we are including files with Karma containing ES modules, which also had dependencies on each other.

Karma loads them with the appended query string, while the dependencies get loaded without it. The browser treats the two instances as different, hence executing their code twice.

These modules contain custom elements based on Lit Element, but the browser doesn't support defining the same element twice, so the tests result in errors.

We eventually took a radically different approach, so this fix is not important to us anymore, but I can imagine it can still hinder other Karma users in similar situations.

**Comment by johnjbarton** [comment]
Ok thanks, it looks like we should not go forward here.

**Pull request closed without merging**
