### PR TITLE
Bump socket.io for iojs 2.1.0

### PR DESCRIPTION
**Pull request by lygstate**

### CODE REVIEW

**Comment by Dignifiedquire** [comment]
Master builds on iojs@2 run fine on travis, as well as on my local machine, so I don't see why this would be needed. Could you explain please.

**Comment by lygstate** [comment]
Sorry, it's caused by long path problem, i've already report to node-gyp
```
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  bufferutil.cc
..\src\bufferutil.cc(32): warning C4996: 'NanSymbol': was declared deprecated [C:\CI-Cor\node_modules\karma\node_modules\socket.io\node_modules\socke
t.io-client\node_modules\engine.io-client\node_modules\ws\build\bufferutil.vcxproj]
          C:\CI-Cor\node_modules\karma\node_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_module
  s\nan\nan.h(616) : see declaration of 'NanSymbol'
  win_delay_load_hook.c
c1 : fatal error C1083: Cannot open source file: '..\..\..\..\..\..\..\..\..\..\..\..\Users\lygstate\AppData\Roaming\npm\node_modules\npm\node_module
s\node-gyp\src\win_delay_load_hook.c': No such file or directory [C:\CI-Cor\node_modules\karma\node_modules\socket.io\node_modules\socket.io-client\n
ode_modules\engine.io-client\node_modules\ws\build\bufferutil.vcxproj]
  validation.cc
..\src\validation.cc(112): warning C4996: 'NanSymbol': was declared deprecated [C:\CI-Cor\node_modules\karma\node_modules\socket.io\node_modules\sock
et.io-client\node_modules\engine.io-client\node_modules\ws\build\validation.vcxproj]
          C:\CI-Cor\node_modules\karma\node_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_module
  s\nan\nan.h(616) : see declaration of 'NanSymbol'
  win_delay_load_hook.c
c1 : fatal error C1083: Cannot open source file: '..\..\..\..\..\..\..\..\..\..\..\..\Users\lygstate\AppData\Roaming\npm\node_modules\npm\node_module
s\node-gyp\src\win_delay_load_hook.c': No such file or directory [C:\CI-Cor\node_modules\karma\node_modules\socket.io\node_modules\socket.io-client\n
ode_modules\engine.io-client\node_modules\ws\build\validation.vcxproj]
npm WARN optional dep failed, continuing utf-8-validate@1.1.0
```

**Comment by lygstate** [comment]
I am confused, the upper comment is my own problem, The master have the following problems,
Maybe you need have a look.

```

C:\CI-Cor>npm install https://github.com/karma-runner/karma.git#master --msvs_version=2013
npm WARN package.json DomParserSrc@1.0.0 No README data
npm WARN package.json DomParserSrc@1.0.0 No license field.
npm WARN optional dep failed, continuing fsevents@0.3.6
-


> ws@0.4.32 install C:\CI-Cor\node_modules\karma\node_modules\socket.io\node_modules\socket.io-client\node_modules\ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

\
C:\CI-Cor\node_modules\karma\node_modules\socket.io\node_modules\socket.io-client\node_modules\ws>if not defined npm_config_node_gyp (node "C:\Users\l
ygstate\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (rebuild)
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  bufferutil.cc
C:\CI-Cor\node_modules\karma\node_modules\socket.io\node_modules\socket.io-client\node_modules\ws\node_modules\nan\nan.h(409): error C2039: 'External
AsciiStringResource' : is not a member of 'v8::String' [C:\CI-Cor\node_modules\karma\node_modules\socket.io\node_modules\socket.io-client\node_module
s\ws\build\bufferutil.vcxproj]
          C:\Users\lygstate\.node-gyp\2.1.0\deps\v8\include\v8.h(1955) : see declaration of 'v8::String'
C:\CI-Cor\node_modules\karma\node_modules\socket.io\node_modules\socket.io-client\node_modules\ws\node_modules\nan\nan.h(409): error C2065: 'External
AsciiStringResource' : undeclared identifier [C:\CI-Cor\node_modules\karma\node_modules\socket.io\node_modules\socket.io-client\node_modules\ws\build
\bufferutil.vcxproj]
C:\CI-Cor\node_modules\karma\node_modules\socket.io\node_modules\socket.io-client\node_modules\ws\node_modules\nan\nan.h(409): error C2065: 'resource
' : undeclared identifier [C:\CI-Cor\node_modules\karma\node_modules\socket.io\node_modules\socket.io-client\node_modules\ws\build\bufferutil.vcxproj
]
C:\CI-Cor\node_modules\karma\node_modules\socket.io\node_modules\socket.io-client\node_modules\ws\node_modules\nan\nan.h(409): error C2448: 'NanNew'
: function-style initializer appears to be a function definition [C:\CI-Cor\node_modules\karma\node_modules\socket.io\node_modules\socket.io-client\n
ode_modules\ws\build\bufferutil.vcxproj]
C:\CI-Cor\node_modules\karma\node_modules\socket.io\node_modules\socket.io-client\node_modules\ws\node_modules\nan\nan.h(1728): error C2039: 'IsExter
nalAscii' : is not a member of 'v8::String' [C:\CI-Cor\node_modules\karma\node_modules\socket.io\node_modules\socket.io-client\node_modules\ws\build\
bufferutil.vcxproj]
          C:\Users\lygstate\.node-gyp\2.1.0\deps\v8\include\v8.h(1955) : see declaration of 'v8::String'
C:\CI-Cor\node_modules\karma\node_modules\socket.io\node_modules\socket.io-client\node_modules\ws\node_modules\nan\nan.h(1729): error C2039: 'Externa
lAsciiStringResource' : is not a member of 'v8::String' [C:\CI-Cor\node_modules\karma\node_modules\socket.io\node_modules\socket.io-client\node_modul
es\ws\build\bufferutil.vcxproj]
          C:\Users\lygstate\.node-gyp\2.1.0\deps\v8\include\v8.h(1955) : see declaration of 'v8::String'
C:\CI-Cor\node_modules\karma\node_modules\socket.io\node_modules\socket.io-client\node_modules\ws\node_modules\nan\nan.h(1729): error C4430: missing
type specifier - int assumed. Note: C++ does not support default-int [C:\CI-Cor\node_modules\karma\node_modules\socket.io\node_modules\socket.io-clie
nt\node_modules\ws\build\bufferutil.vcxproj]
C:\CI-Cor\node_modules\karma\node_modules\socket.io\node_modules\socket.io-client\node_modules\ws\node_modules\nan\nan.h(1729): error C2143: syntax e
rror : missing ';' before '*' [C:\CI-Cor\node_modules\karma\node_modules\socket.io\node_modules\socket.io-client\node_modules\ws\build\bufferutil.vcx
proj]
C:\CI-Cor\node_modules\karma\node_modules\socket.io\node_modules\socket.io-client\node_modules\ws\node_modules\nan\nan.h(1729): error C2065: 'ext' :
undeclared identifier [C:\CI-Cor\node_modules\karma\node_modules\socket.io\node_modules\socket.io-client\node_modules\ws\build\bufferutil.vcxproj]
C:\CI-Cor\node_modules\karma\node_modules\socket.io\node_modules\socket.io-client\node_modules\ws\node_modules\nan\nan.h(1730): error C2065: 'ext' :
undeclared identifier [C:\CI-Cor\node_modules\karma\node_modules\socket.io\node_modules\socket.io-client\node_modules\ws\build\bufferutil.vcxproj]
C:\CI-Cor\node_modules\karma\node_modules\socket.io\node_modules\socket.io-client\node_modules\ws\node_modules\nan\nan.h(1730): error C2039: 'GetExte
rnalAsciiStringResource' : is not a member of 'v8::String' [C:\CI-Cor\node_modules\karma\node_modules\socket.io\node_modules\socket.io-client\node_mo
dules\ws\build\bufferutil.vcxproj]
          C:\Users\lygstate\.node-gyp\2.1.0\deps\v8\include\v8.h(1955) : see declaration of 'v8::String'
C:\CI-Cor\node_modules\karma\node_modules\socket.io\node_modules\socket.io-client\node_modules\ws\node_modules\nan\nan.h(1731): error C2065: 'ext' :
undeclared identifier [C:\CI-Cor\node_modules\karma\node_modules\socket.io\node_modules\socket.io-client\node_modules\ws\build\bufferutil.vcxproj]
C:\CI-Cor\node_modules\karma\node_modules\socket.io\node_modules\socket.io-client\node_modules\ws\node_modules\nan\nan.h(1731): error C2227: left of
'->data' must point to class/struct/union/generic type [C:\CI-Cor\node_modules\karma\node_modules\socket.io\node_modules\socket.io-client\node_module
s\ws\build\bufferutil.vcxproj]
          type is 'unknown-type'
C:\CI-Cor\node_modules\karma\node_modules\socket.io\node_modules\socket.io-client\node_modules\ws\node_modules\nan\nan.h(1732): error C2065: 'ext' :
undeclared identifier [C:\CI-Cor\node_modules\karma\node_modules\socket.io\node_modules\socket.io-client\node_modules\ws\build\bufferutil.vcxproj]
C:\CI-Cor\node_modules\karma\node_modules\socket.io\node_modules\socket.io-client\node_modules\ws\node_modules\nan\nan.h(1732): error C2227: left of
'->length' must point to class/struct/union/generic type [C:\CI-Cor\node_modules\karma\node_modules\socket.io\node_modules\socket.io-client\node_modu
les\ws\build\bufferutil.vcxproj]
          type is 'unknown-type'
  validation.cc
C:\CI-Cor\node_modules\karma\node_modules\socket.io\node_modules\socket.io-client\node_modules\ws\node_modules\nan\nan.h(409): error C2039: 'External
AsciiStringResource' : is not a member of 'v8::String' [C:\CI-Cor\node_modules\karma\node_modules\socket.io\node_modules\socket.io-client\node_module
s\ws\build\validation.vcxproj]
          C:\Users\lygstate\.node-gyp\2.1.0\deps\v8\include\v8.h(1955) : see declaration of 'v8::String'
C:\CI-Cor\node_modules\karma\node_modules\socket.io\node_modules\socket.io-client\node_modules\ws\node_modules\nan\nan.h(409): error C2065: 'External
AsciiStringResource' : undeclared identifier [C:\CI-Cor\node_modules\karma\node_modules\socket.io\node_modules\socket.io-client\node_modules\ws\build
\validation.vcxproj]
C:\CI-Cor\node_modules\karma\node_modules\socket.io\node_modules\socket.io-client\node_modules\ws\node_modules\nan\nan.h(409): error C2065: 'resource
' : undeclared identifier [C:\CI-Cor\node_modules\karma\node_modules\socket.io\node_modules\socket.io-client\node_modules\ws\build\validation.vcxproj
]
C:\CI-Cor\node_modules\karma\node_modules\socket.io\node_modules\socket.io-client\node_modules\ws\node_modules\nan\nan.h(409): error C2448: 'NanNew'
: function-style initializer appears to be a function definition [C:\CI-Cor\node_modules\karma\node_modules\socket.io\node_modules\socket.io-client\n
ode_modules\ws\build\validation.vcxproj]
C:\CI-Cor\node_modules\karma\node_modules\socket.io\node_modules\socket.io-client\node_modules\ws\node_modules\nan\nan.h(1728): error C2039: 'IsExter
nalAscii' : is not a member of 'v8::String' [C:\CI-Cor\node_modules\karma\node_modules\socket.io\node_modules\socket.io-client\node_modules\ws\build\
validation.vcxproj]
          C:\Users\lygstate\.node-gyp\2.1.0\deps\v8\include\v8.h(1955) : see declaration of 'v8::String'
C:\CI-Cor\node_modules\karma\node_modules\socket.io\node_modules\socket.io-client\node_modules\ws\node_modules\nan\nan.h(1729): error C2039: 'Externa
lAsciiStringResource' : is not a member of 'v8::String' [C:\CI-Cor\node_modules\karma\node_modules\socket.io\node_modules\socket.io-client\node_modul
es\ws\build\validation.vcxproj]
          C:\Users\lygstate\.node-gyp\2.1.0\deps\v8\include\v8.h(1955) : see declaration of 'v8::String'
C:\CI-Cor\node_modules\karma\node_modules\socket.io\node_modules\socket.io-client\node_modules\ws\node_modules\nan\nan.h(1729): error C4430: missing
type specifier - int assumed. Note: C++ does not support default-int [C:\CI-Cor\node_modules\karma\node_modules\socket.io\node_modules\socket.io-clie
nt\node_modules\ws\build\validation.vcxproj]
C:\CI-Cor\node_modules\karma\node_modules\socket.io\node_modules\socket.io-client\node_modules\ws\node_modules\nan\nan.h(1729): error C2143: syntax e
rror : missing ';' before '*' [C:\CI-Cor\node_modules\karma\node_modules\socket.io\node_modules\socket.io-client\node_modules\ws\build\validation.vcx
proj]
C:\CI-Cor\node_modules\karma\node_modules\socket.io\node_modules\socket.io-client\node_modules\ws\node_modules\nan\nan.h(1729): error C2065: 'ext' :
undeclared identifier [C:\CI-Cor\node_modules\karma\node_modules\socket.io\node_modules\socket.io-client\node_modules\ws\build\validation.vcxproj]
C:\CI-Cor\node_modules\karma\node_modules\socket.io\node_modules\socket.io-client\node_modules\ws\node_modules\nan\nan.h(1730): error C2065: 'ext' :
undeclared identifier [C:\CI-Cor\node_modules\karma\node_modules\socket.io\node_modules\socket.io-client\node_modules\ws\build\validation.vcxproj]
C:\CI-Cor\node_modules\karma\node_modules\socket.io\node_modules\socket.io-client\node_modules\ws\node_modules\nan\nan.h(1730): error C2039: 'GetExte
rnalAsciiStringResource' : is not a member of 'v8::String' [C:\CI-Cor\node_modules\karma\node_modules\socket.io\node_modules\socket.io-client\node_mo
dules\ws\build\validation.vcxproj]
          C:\Users\lygstate\.node-gyp\2.1.0\deps\v8\include\v8.h(1955) : see declaration of 'v8::String'
C:\CI-Cor\node_modules\karma\node_modules\socket.io\node_modules\socket.io-client\node_modules\ws\node_modules\nan\nan.h(1731): error C2065: 'ext' :
undeclared identifier [C:\CI-Cor\node_modules\karma\node_modules\socket.io\node_modules\socket.io-client\node_modules\ws\build\validation.vcxproj]
C:\CI-Cor\node_modules\karma\node_modules\socket.io\node_modules\socket.io-client\node_modules\ws\node_modules\nan\nan.h(1731): error C2227: left of
'->data' must point to class/struct/union/generic type [C:\CI-Cor\node_modules\karma\node_modules\socket.io\node_modules\socket.io-client\node_module
s\ws\build\validation.vcxproj]
          type is 'unknown-type'
C:\CI-Cor\node_modules\karma\node_modules\socket.io\node_modules\socket.io-client\node_modules\ws\node_modules\nan\nan.h(1732): error C2065: 'ext' :
undeclared identifier [C:\CI-Cor\node_modules\karma\node_modules\socket.io\node_modules\socket.io-client\node_modules\ws\build\validation.vcxproj]
C:\CI-Cor\node_modules\karma\node_modules\socket.io\node_modules\socket.io-client\node_modules\ws\node_modules\nan\nan.h(1732): error C2227: left of
'->length' must point to class/struct/union/generic type [C:\CI-Cor\node_modules\karma\node_modules\socket.io\node_modules\socket.io-client\node_modu
les\ws\build\validation.vcxproj]
          type is 'unknown-type'
karma@0.12.33 node_modules\karma
├── di@0.0.1
├── graceful-fs@2.0.3
├── colors@0.6.2
├── rimraf@2.2.8
├── mime@1.2.11
├── q@0.9.7
├── optimist@0.6.1 (wordwrap@0.0.3, minimist@0.0.10)
├── minimatch@0.2.14 (sigmund@1.0.1, lru-cache@2.6.4)
├── source-map@0.1.43 (amdefine@0.1.0)
├── glob@3.2.11 (inherits@2.0.1, minimatch@0.3.0)
├── lodash@2.4.2
├── log4js@0.6.25 (async@0.2.10, underscore@1.8.2, readable-stream@1.0.33, semver@4.3.4)
├── useragent@2.0.10 (lru-cache@2.2.4)
├── http-proxy@0.10.4 (pkginfo@0.3.0, utile@0.2.1)
├── chokidar@1.0.1 (arrify@1.0.0, is-glob@1.1.3, glob-parent@1.2.0, async-each@0.1.6, is-binary-path@1.0.1, readdirp@1.3.0, anymatch@1.3.0)
├── connect@2.26.6 (fresh@0.2.4, cookie-signature@1.0.5, pause@0.0.1, cookie@0.1.2, response-time@2.0.1, vhost@3.0.0, bytes@1.0.0, on-headers@1.0.0
, media-typer@0.3.0, basic-auth-connect@1.0.0, parseurl@1.3.0, depd@0.4.5, connect-timeout@1.3.0, cookie-parser@1.3.5, qs@2.2.4, debug@2.0.0, finalhan
dler@0.2.0, method-override@2.2.0, serve-favicon@2.1.7, morgan@1.3.2, type-is@1.5.7, multiparty@3.3.2, compression@1.1.2, errorhandler@1.2.4, body-par
ser@1.8.4, serve-static@1.6.5, serve-index@1.2.1, csurf@1.6.6, express-session@1.8.2)
└── socket.io@0.9.16 (base64id@0.1.0, policyfile@0.0.4, redis@0.7.3, socket.io-client@0.9.16)

C:\CI-Cor>
```

**Comment by Dignifiedquire** [comment]
The output that you pasted looks like they were just warnings and that it actually finished installing

**Comment by lygstate** [comment]
```


C:\CI-Cor\node_modules\karma\node_modules\socket.io\node_modules\socket.io-client\node_modules\ws\node_modules\nan\nan.h(1730): error C2039: 'GetExte
rnalAsciiStringResource' : is not a member of 'v8::String' [C:\CI-Cor\node_modules\karma\node_modules\socket.io\node_modules\socket.io-client\node_mo
dules\ws\build\bufferutil.vcxproj]

```

It's error, please search for error.

**Comment by Dignifiedquire** [comment]
Okay, yes it looks like it's an issue with socket.io and windows and an upgraded version of `nan`. There is already a PR that properly updates socket.io to the latest version which should fix the issue. If you want you can try that one out: #1404

**Comment by Dignifiedquire** [comment]
I really don't want to depend on the master branch of socket.io, hopefully they'll publish a new version soon which we can then use. I'll revisit when moving socket.io > 1.0 into the stable release.

**Pull request closed without merging**
