### PR TITLE
output UserAgent string verbatim if it cannot be parsed

### PR DESCRIPTION
**Pull request by tailsu**

### CODE REVIEW

**Comment by tailsu** [comment]
I signed it!

**Comment by Dignifiedquire** [comment]
Thanks for the contribution, could you please make sure your commit matches our [convention](http://karma-runner.github.io/0.12/dev/git-commit-msg.html) and add a unit test for this?

**Comment by tailsu** [comment]
Done and done. :ghost:

**Comment by Dignifiedquire** [comment]
One more thing, could you please rebase onto the latest `canary` version please

**Comment by tailsu** [comment]
Done.

**Comment by Dignifiedquire** [comment]
Thanks!

**Pull request merged**
