### PR TITLE
fix(context): Updated postMessage listener to stop validating non-Karma messages

### LINKED ISSUE #2239: Received `postMessage` for "undefined" but the method doesn't exist
### Expected behavior

Projects that use postMessage should not break karma

### Actual behavior

This change makes karma incompatible with projects that use postMessage https://github.com/karma-runner/karma/commit/81b1f04c70eb14ca675f60b3f374bb50b96d80fe#diff-e935b6c040afc12b7a014e625f4f0cedR40

### Enviroment Details

https://bitbucket.org/atlassian/simple-xdm/addon/pipelines/home#!/results/%7Bcc56070d-5ec1-43f2-ab8e-07cf4e6309a5%7D

- Karma version (output of `karma --version`): 1.1.1
- Relevant part of your `karma.config.js` file N/A

### Steps to reproduce the behaviour

1. Write test that uses postMessage
2. Run test with karma
3. Karma receives postMessage it doesn't expect and balks

Consider changing log to warn rather than error or namespacing your postMessages

### PR DESCRIPTION
**Pull request by twolfson**
As reported in #2239, our current `postMessage` hook is looking at all post messages, not only the ones for Karma. In this PR:

- Moved to namespaced `postMessage` variable checks
- Updated `postMessage` logic to only assert if a truthy method was given
- Fixes #2239 

/cc @dignifiedquire

### CODE REVIEW

**Comment by dignifiedquire** [comment]
Thanks looks good to me. Any ideas yet on how to add a test for `postMessage`?

**Comment by twolfson** [comment]
It should be something like adding a `postMessage` call in one of our test suites and verifying nothing is thrown but as mentioned in #2239, I ran out of time to explore that =/

**Comment by AnilRedshift** [comment]
Is there an ETA for this fix - it is causing our builds on Safari to fail ~50% of the time. The fix proposed seems reasonable to me.

**Comment by al-the-x** [comment]
@AnilRedshift I can confirm (along with others from #2239) that rolling back to 1.0.0 fixes the issue for immediate purposes.

**Comment by dignifiedquire** [comment]
release will happen next week

**Comment by dignifiedquire** [comment]
Thanks :octocat:

**Pull request merged**
