### PR TITLE
Include karma bin in package.json

### PR DESCRIPTION
**Pull request by dazld**

### CODE REVIEW

**Comment by pkozlowski-opensource** [comment]
@dazld why? Didn't `karma-cli` work for you?

**Comment by dazld** [comment]
hey, when you run `npm test`, for example, then npm automatically includes the `.bin` folder in its path for the script which is being run. this means you don't need either a global install of karma, nor do you have to reference the full path to the bin, and can do stuff like..

```
..
"scripts": {
    "test": "karma start"
  },
..
```
etc.

**Comment by dazld** [comment]
does that make sense..? I know it's a simple change.

**Comment by maksimr** [comment]
@dazld you can install `karma-cli` locally to the project and then you example above will work.

https://github.com/karma-runner/karma/issues/1078

**Comment by dazld** [comment]
got it, thanks.

**Comment by peter-mouland** [comment]
I was also going to do this PR.  Is there a reason why you want the extra step of having to install another dependency rather than just putting the path in to the package.json?

**Pull request closed without merging**
