### PR TITLE
docs: Including reference to Windows port of nvm

### PR DESCRIPTION
**Pull request by aaronpowell**

### CODE REVIEW

**Comment by aaronpowell** [comment]
CLA signed!

**Comment by dignifiedquire** [comment]
Thanks can you change the commit message to follow our guidelines please?

**Comment by aaronpowell** [comment]
ah, didn't realise there was a convention, sorry @dignifiedquire, I'll get that resolved :smile:

**Comment by aaronpowell** [comment]
I wasn't sure how to set the `footer` part since it doesn't close any specific bug.

**Comment by dignifiedquire** [comment]
Thanks, you can leave out the footer if there is nothing to reference.

**Pull request merged**
