### PR TITLE
feat: Support for custom context and/or debug html files

### PR DESCRIPTION
**Pull request by Sanjo**
This is a replacement for the pull request https://github.com/karma-runner/karma/pull/1360. I have updated the code for the latest master. There was also a bug in the old pull request code because requestUrl was overwritten. I have also added support for absolute paths.

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 94824e8645fd932c5f49c341232080be7bb47465
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at http://karma-runner.github.io/0.13/dev/git-commit-msg.html

---
This message was auto-generated by https://gitcop.com

**Comment by Sanjo** [comment]
If you tell me the correct scope, I can add it to the commit message.

**Comment by Dignifiedquire** [comment]
You can leave the scope out that's okay, but this is still missing some stuff I mentioned in the other PR

> * update the docs so people can find these options
> * these options shouldn't be nested in the client configs, they should be top level and default to the ones karma brings
> * path normalization and setting defaults should be done in lib/config.js

**Comment by Dignifiedquire** [comment]
ping @Sanjo

**Comment by Sanjo** [comment]
The changes that you wrote in https://github.com/karma-runner/karma/pull/1586#issuecomment-140898804 still need to be done.

**Comment by marthinus-engelbrecht** [comment]
:+1: It makes better sense. I commented on another issues and didn't get a response fast enough for the urgency I needed to fix it on my side. Currently pointing at the fork. Will look at the other suggestion, framework agnostic sounds better to me.

**Comment by dignifiedquire** [comment]
Closing in favor of #1825

**Comment by durgesh-priyaranjan** [comment]
Is this change published to npm?

**Pull request closed without merging**
