### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by jgorset**
Silly thing, really, but considering that "TDD" stands for "test-driven development" this becomes "test-driven development development". This bothers the neckbeard.

### CODE REVIEW

**Comment by zzo** [comment]
#merge

**Comment by Dignifiedquire** [comment]
Thanks for this, could you please update your commit message according to our [convention](http://karma-runner.github.io/0.12/dev/git-commit-msg.html) ?

**Comment by Dignifiedquire** [comment]
Merged as b8e1bf162a7ac1753486eaaaa1aa4cc54f99a637

**Comment by jgorset** [comment]
Sorry about that, @Dignifiedquire, I must have missed your comment from before.

**Pull request closed without merging**
