### PR TITLE
Update dev dependencies

### LINKED ISSUE #1294: grunt-jscs-checker warning on npm install
### Steps to reproduce:
```sh
$ npm i
npm WARN deprecated grunt-jscs-checker@0.6.2: Package was renamed to 'grunt-jscs'
```

Looks like this was renamed to [grunt-jscs](https://www.npmjs.com/package/grunt-jscs).

### PR DESCRIPTION
**Pull request by Dignifiedquire**
Fixes  #1294

### CODE REVIEW

**Comment by maksimr** [comment]
LGTM

**Comment by zzo** [comment]
#merge

**Comment by Dignifiedquire** [comment]
@karmarunnerbot he is back :)

**Comment by zzo** [comment]
Yes!  Need to find a PR with bug fixes/changes to test the pushing to npm
but everything else is looking good! The karmabot script is looking for log
messages with:

fix()
or
feat()

and then it will auto-push to npm as well as merging.

Any suggestions?

**Comment by Dignifiedquire** [comment]
@zzo how about https://github.com/karma-runner/karma/pull/1401? 

while you are at it could you whitelist me, so I can trigger merges as well please?

**Comment by zzo** [comment]
Ok I kicked it off and added you with #merge powers.
There still is a problem with the script staying alive :)   Assuming this
gets successfully pushed to npm I'm hoping to fix the 'stay alive' part
today & then we'll be gtg for all future #merge magic.

**Comment by Dignifiedquire** [comment]
> Ok I kicked it off and added you with #merge powers.

Cool thanks.

Do you think you are free either later today or in the next days to have a quick call about some organizational stuff/1.0 release?

**Comment by zzo** [comment]
yes can do this afternoon at 2pm or 3pm PST or tomorrow afternoon at
2pm-4pm PST - any of those times work? thanks
of course the build/push failed ... :(

**Comment by Dignifiedquire** [comment]
2pm PST today would work for me

**Comment by Dignifiedquire** [comment]
@zzo I've updated https://github.com/karma-runner/karma/issues/1406#issue-77074305 so we have something to talk about

**Comment by zzo** [comment]
ok 2pm - google hangout 'karma' work?

**Comment by Dignifiedquire** [comment]
> ok 2pm - google hangout 'karma' work?

:+1:

**Pull request merged**
