### PR TITLE
Include Node 5.x versions

### PR DESCRIPTION
**Pull request by buzinas**

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: ea87a74cfe89783ae684b88c038a931f4cce5451
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at http://karma-runner.github.io/0.13/dev/git-commit-msg.html

---
This message was auto-generated by https://gitcop.com

**Comment by buzinas** [comment]
I signed it!

**Comment by zzo** [comment]
lgtm thanks!

**Comment by Dignifiedquire** [comment]
@zzo please don't merge prs not following the commit message convention :(

**Comment by zzo** [comment]
Ach!! My bad sorry!!!

**Pull request merged**
