### PR TITLE
Prep for 2.0

### PR DESCRIPTION
**Pull request by dignifiedquire**

### CODE REVIEW

**Comment by dignifiedquire** [comment]
Need to update the cucumber step defs to fix the tests

**Comment by dignifiedquire** [comment]
Need to figure out why node 4 and 6 are unhappy

**Comment by johnjbarton** [comment]
Looks like you need to prevent coffeescript 2.x.  
https://github.com/karma-runner/karma/blob/master/package.json#L366
It requires node 6 or higher.
https://github.com/jashkenas/coffeescript/blob/master/package.json

**Comment by EzraBrooks** [comment]
Did you intend to add a Yarn lockfile? The project doesn’t currently include a lockfile for neither npm nor Yarn. Will 2.0 be taking a stance on which package manager to use?

**Comment by dignifiedquire** [comment]
@EzraBrooks I have certain opinions on the matter, but I am not yet sure if it makes sense to add them to karma.

**Comment by dignifiedquire** [comment]
@johnjbarton interesting, I guess this is only a devdependency so it should be fine to stay on the 1.x branch for now

**Comment by EzraBrooks** [comment]
Would it be useful for the project to adopt TypeScript's type-checking as part of the lint stage? Just by enabling `ts-check` on some of the files in the project, there's a lot of ambiguous typing that becomes very obvious. Since you can use the type checking without converting your code to TypeScript, I thought I'd suggest it.

**Comment by dignifiedquire** [comment]
@EzraBrooks I like the idea, but lets make a separate pr/issue about it.

**Comment by dignifiedquire** [comment]
This should be ready

**Pull request merged**
