### PR TITLE
fix(launcher): send sigkill on timeout when force killing

### PR DESCRIPTION
**Pull request by kakadiya91**
@dignifiedquire This is in response to bug we are seeing where karma hangs because it is unable to force kill chrome, possibly https://github.com/karma-runner/karma/issues/24#issuecomment-216249098

### CODE REVIEW

**Comment by kakadiya91** [comment]
I signed it!

**Comment by dignifiedquire** [comment]
Thanks, can you change the commit message to be`fix(launcher:` instead of `bug` please?

**Comment by kakadiya91** [comment]
@dignifiedquire, i updated the commit message, thanks.

**Comment by modulesio** [comment]
@dignifiedquire Any ETA on this one landing?

**Pull request merged**
