### PR TITLE
chore(travis): run travis tests on node@0.12 and io.js

### PR DESCRIPTION
**Pull request by demohi**

### CODE REVIEW

**Comment by Krinkle** [comment]
Issue #1328.

**Comment by ilanbiala** [comment]
It doesn't pass tests, so this can't just be merged in to close #1328.

**Comment by maksimr** [comment]
@demoh pls change commit message [following convention](http://karma-runner.github.io/0.12/dev/git-commit-msg.html)

Thanks

**Comment by yngvebn** [comment]
This is really holding us back.. If the only thing stopping it is a git commit --amend, can you please fix it @demohi ? :)

**Comment by demohi** [comment]
OK I will fix it. @yngvebn

**Comment by yngvebn** [comment]
Excellent! :)

**Comment by maksimr** [comment]
@yngvebn why it's holding you?
This is simple run karma tests on node@0.12 and io.js

**Comment by demohi** [comment]
@yngvebn I fixed it.

**Comment by maksimr** [comment]
@demohi Thanks

**Pull request merged**
