### PR TITLE
docs: Include jasmine-core in installation instructions

### PR DESCRIPTION
**Pull request by camargo**
Update to include jasmine-core in install doc, which is a peer dependency of karma-jasmine

### CODE REVIEW

**Comment by camargo** [comment]
I signed it

**Comment by dignifiedquire** [comment]
Thanks, can you please update the commit message to follow our [convention](http://karma-runner.github.io/1.0/dev/git-commit-msg.html)

**Comment by camargo** [comment]
@dignifiedquire I think I did it correctly. Let me know if it needs further altering, thanks

**Comment by camargo** [comment]
I'm going to open a new one

**Pull request closed without merging**
