### PR TITLE
fix(deps): pin colors package to 1.4.0 due to security vulnerability

### PR DESCRIPTION
**Pull request by sergei-startsev**
Another one, hopefully contains all required changes :weary:

Pin `colors` package to `1.4.0` version due to security vulnerability. See details:
- [1.4.0...1.4.2 diff](https://diff.intrinsic.com/colors/1.4.0/1.4.2)
- https://github.com/Marak/colors.js/issues/285
- https://www.theverge.com/2022/1/9/22874949/developer-corrupts-open-source-libraries-projects-affected
- https://www.bleepingcomputer.com/news/security/dev-corrupts-npm-libs-colors-and-faker-breaking-thousands-of-apps/

### CODE REVIEW

**Comment by ellyxc** [comment]
is it possible if we set in config `color:false` don't load/require the color to avoid similar issue in the future?

**Review by devoto13 — APPROVED** [review]
Thanks for the PR!

**Comment by sergei-startsev** [comment]
> is it possible if we set in config `color:false` don't load/require the color to avoid similar issue in the future?

I'd rather replace `colors` with another package (e.g. [chalk](https://www.npmjs.com/package/chalk)) in the long run.

**Comment by simonl65** [comment]
Would be great if you would merge this - if only as a temporary workaround - as it's likely affecting MANY users worldwide ;-)

Happy for you to use an alternative, but delays cost lots of hair pulling.

**Comment by SerkanSipahi** [comment]
Here is an interim solution https://github.com/nrwl/nx/issues/8450#issuecomment-1008759313 !

**Comment by nicojs** [comment]
Update: NPM has pulled versions 1.4.2 and 1.4.1. Installing the `latest` colors version will give you `1.4.0`. This means that the problem is solved for karma users today, but this PR should still be merged IMO, for the karma users of tomorrow. (and later be replaced with a package that has a responsible maintainer)

**Comment by jginsburgn** [comment]
@sergei-startsev please fix the CI tests :)

**Comment by jginsburgn** [comment]
> @sergei-startsev please fix the CI tests :)

Sorry, I just realized that CI will turn green after https://github.com/karma-runner/karma/pull/3742 is merged. Let's just wait for that.

**Comment by MannyPamintuanAtCare** [comment]
closes #3740

**Review by jginsburgn — APPROVED** [review]

**Comment by simonl65** [comment]
Thank you

**Pull request merged**
