### PR TITLE
fix(client): don't crash if receive array-like results.

### LINKED ISSUE #2061: Error getting failed test output in IE11 without iframe
### Expected behavior

Output of a failed test in IE11 gets logged in the console.
### Actual behavior

An error is raised:

```
TypeError: result.suite.join is not a function
    at specFailure (/Users/kostia/Code/tmp/karma-ie-debug/node_modules/karma/lib/reporters/base.js:94:33)
    at onSpecComplete (/Users/kostia/Code/tmp/karma-ie-debug/node_modules/karma/lib/reporters/base.js:80:12)
    at null.<anonymous> (/Users/kostia/Code/tmp/karma-ie-debug/node_modules/karma/lib/events.js:13:22)
    at emitTwo (events.js:100:13)
    at emit (events.js:185:7)
    at onResult (/Users/kostia/Code/tmp/karma-ie-debug/node_modules/karma/lib/browser.js:216:13)
    at Array.forEach (native)
    at onResult (/Users/kostia/Code/tmp/karma-ie-debug/node_modules/karma/lib/browser.js:206:21)
    at Socket.<anonymous> (/Users/kostia/Code/tmp/karma-ie-debug/node_modules/karma/lib/events.js:13:22)
    at emitOne (events.js:95:20)
    at Socket.emit (events.js:182:7)
    at Socket.onevent (/Users/kostia/Code/tmp/karma-ie-debug/node_modules/socket.io/lib/socket.js:335:8)
    at Socket.onpacket (/Users/kostia/Code/tmp/karma-ie-debug/node_modules/socket.io/lib/socket.js:295:12)
    at Client.ondecoded (/Users/kostia/Code/tmp/karma-ie-debug/node_modules/socket.io/lib/client.js:193:14)
    at Decoder.Emitter.emit (/Users/kostia/Code/tmp/karma-ie-debug/node_modules/component-emitter/index.js:134:20)
    at Decoder.add (/Users/kostia/Code/tmp/karma-ie-debug/node_modules/socket.io-parser/index.js:247:12)
```
### Enviroment Details
- "jasmine": "2.4.1",
- "karma": "0.13.22"
- "karma-jasmine": "0.3.6"
- "karma-sauce-launcher": "0.3.0"
- `conf.js`

``` javascript
module.exports = function(config) {
  config.set({
    singleRun: true,
    frameworks: ['jasmine'],
    files: ['test_spec.js'],
    client: {
      useIframe: false
    },
    browsers: ['ie'],
    customLaunchers: {
      ie: {
        base: 'SauceLabs',
        os: 'Windows 7',
        browserName: 'internet explorer',
        version: '11'
      }
    },
    sauceLabs: {
      startConnect: false,
      tunnelIdentifier: process.env.SAUCELABS_TUNNEL_IDENTIFIER,
      testName: 'debug',
    },
  });
};
```
### Steps to reproduce the behaviour

Simply run a failing spec:

``` js
// test_spec.js
describe('when running failing specs on IE11', function() {
  it('raises an error while capturing test output', function() {
    expect(true).toBe(false);
  });
});
```

The crucial part it the switch `client.useIframe`. The error is only raise if the iframe is disabled as in my config.

### PR DESCRIPTION
**Pull request by kostia**
fixes #2061

### CODE REVIEW

**Comment by kostia** [comment]
I signed it!

**Comment by dignifiedquire** [comment]
Thanks, have you tested this in IE 7-10? we need to support that, and `hasOwnProperty` and `for in` loops might not work as expected in those browsers.

**Comment by kostia** [comment]
@dignifiedquire Are you sure Karma officially supports all IEs from 7 to 10? Because I cannot make it work neither in IE7, nor in IE10; even without my patch. Or maybe it's Jasmine, which does not support older IEs? Is there another framework for Karma, which maybe supports older IE versions?

**Comment by dignifiedquire** [comment]
This is the setup we are using for testing older versions: https://github.com/karma-runner/karma/blob/master/test/client/karma.conf.js

**Comment by apepper** [comment]
I've also tried to make karma run with IE8 - without success, due toe socket.io errors not related to this PR.

Could you please merge this PR anyway? Currently the state with IE is completely broken, if a spec fail. This PR ensures at least, that it's not broken with IE11.

**Pull request merged**
