### PR TITLE
fix(file-list): do not preprocess up-to-date files

### LINKED ISSUE #2829: "karma run" re-runs preprocessors for unmodified files
### Expected behaviour

Running tests via "karma run" should not run preprocessors for unmodified files.

### Actual behaviour

Running tests via "karma run" always runs preprocessors for all files (including unmodified ones).

### Environment Details

- Karma version (output of `karma --version`): 1.7.1
- Relevant part of your `karma.config.js` file: see steps to reproduce

### Steps to reproduce the behaviour

1. Open https://github.com/babel/karma-babel-preprocessor/tree/v7.0.0 and update "karma" dependency to 1.7.1
2. Run karma server: `./node_modules/karma/bin/karma start`
3. Run karma tests: `./node_modules/karma/bin/karma run`
Output:
```
...
19 09 2017 16:30:15.693:DEBUG [karma]: Refreshing all the files / patterns
19 09 2017 16:30:15.696:DEBUG [preprocessor.babel]: Processing "/home/segrey/samples/karma-babel-preprocessor/test/hello.js".
19 09 2017 16:30:15.728:DEBUG [preprocessor.babel]: Processing "/home/segrey/samples/karma-babel-preprocessor/test/generator.spec.js".
19 09 2017 16:30:15.735:DEBUG [preprocessor.babel]: Processing "/home/segrey/samples/karma-babel-preprocessor/test/hello.spec.js".
19 09 2017 16:30:15.741:DEBUG [preprocessor.babel]: Processing "/home/segrey/samples/karma-babel-preprocessor/test/generator.js".
...
```

Expected behaviour: unmodified files are not processed

### PR DESCRIPTION
**Pull request by segrey**
It improves performance of "karma run" command which refreshes fileList.

Closes #2829

### CODE REVIEW

**Comment by segrey** [comment]
@johnjbarton What do you think about this change? I can add tests if the change is generally OK.

**Comment by johnjbarton** [comment]
Should we worry that we will perform the check even though the preprocess maybe trivial?
Is every preprocess known to be cached?

**Comment by segrey** [comment]
> Should we worry that we will perform the check even though the preprocess maybe trivial?

As I understand, the check is fast enough and shouldn't impact the performance. Also, if I'm not mistaken, `fileList.refresh()` is called from `karma run` command only (`lib/middleware/runner.js`). AFAIK, `karma run` is not used often when running karma tests manually.

>Is every preprocess known to be cached?

Looks like. At least [`fileList.changeFile(filePath)`](https://github.com/karma-runner/karma/blob/c311ac00cef4a957f889ed613238793c0ffa95a2/lib/file-list.js#L232) runs preprocessors for changed files only. It seems OK to preprocess changed files only in `fileList.refresh()` too.

**Comment by johnjbarton** [comment]
Ok please see if you can create a test.

**Comment by segrey** [comment]
Done, please take a look.

**Comment by Havunen** [comment]
This PR probably broke single entry setups? https://github.com/karma-runner/karma/issues/3226

**Pull request merged**
