### PR TITLE
Update Semaphore CI description

### PR DESCRIPTION
**Pull request by dunjardl**

### CODE REVIEW

**Comment by dunjardl** [comment]
I signed it!

**Comment by dignifiedquire** [comment]
thanks

**Comment by dunjardl** [comment]
@dignifiedquire thanks for reviewing the changes :) do you perhaps know when they will be live?

**Comment by dignifiedquire** [comment]
Now: http://karma-runner.github.io/1.0/plus/semaphore.html :)

**Comment by dunjardl** [comment]
@dignifiedquire Thanks :)

**Pull request merged**
