### PR TITLE
feat(preprocessor): Capital letters in binary files extenstions

### LINKED ISSUE #1508: Static binary assets are not served correctly when they have capital letters in extension
When serving static binary assets configured with:
```javascript
files: [
	...
	{pattern: './fixtures/images/*.jpg', included: false, served: true},
	{pattern: './fixtures/images/*.JPG', included: false, served: true},
	...
]
```
Only images with *.jpg extensions are served properly. Capital letters extension shows a 'broken image' icon. This seems to be due to not recognising said image as a binary file. Adding "JPG" to `lib/binary-extensions.json` or modifying `lib/preprocessor.js` condition like so:
```javascript
var thisFileIsBinary = isBinary[path.extname(file.originalPath).toLowerCase()]
```
Solves the problem.

Not sure how to write a failing test for this to submit a fix.

### PR DESCRIPTION
**Pull request by lonelyelk**
Use lower case file extension to detect if it is binary

Closes #1508

### CODE REVIEW

**Comment by lonelyelk** [comment]
I signed it!

**Comment by Dignifiedquire** [comment]
Thanks :octocat:

**Comment by Dignifiedquire** [comment]
Published in `0.13.3`

**Comment by lonelyelk** [comment]
Yay! Even released! Thank you!

**Pull request merged**
